export type Row='FRONT'|'MIDDLE'|'BACK';
export type Keyword='Taunt'|'Shield'|'Rush'|'Silence'|'Ward'|'Foresee'|'Resonance';
export interface EngineCard {id:string;name:string;description?:string;type:'UNIT'|'SPELL';cost:number;attack?:number;health?:number;keywords:Keyword[];damage?:number}
export interface CardInstance extends EngineCard {instanceId:string;ownerId:string;currentAttack:number;currentHealth:number;row?:Row;attacked:boolean;shield:boolean;silenced:boolean;summonedTurn:number}
export interface PlayerState {id:string;leaderHealth:number;maxEnergy:number;energy:number;deck:CardInstance[];hand:CardInstance[];board:Record<Row,CardInstance[]>;graveyard:CardInstance[]}
export interface GameEvent {type:string;playerId?:string;sourceId?:string;targetId?:string;amount?:number;message:string}
export interface GameState {seed:number;rngState:number;turn:number;activePlayerId:string;players:[PlayerState,PlayerState];phase:'MULLIGAN'|'MAIN'|'ENDED';winnerId?:string|null;events:GameEvent[];effectQueue:GameEvent[]}
export type GameAction={type:'MULLIGAN';playerId:string;cardInstanceIds:string[]}|{type:'PLAY_CARD';playerId:string;cardInstanceId:string;row?:Row;targetId?:string}|{type:'ATTACK';playerId:string;attackerId:string;targetId:string}|{type:'END_TURN';playerId:string}|{type:'CONCEDE';playerId:string};
export type Result={ok:true;state:GameState}|{ok:false;state:GameState;error:string};
const rows:Row[]=['FRONT','MIDDLE','BACK'];
const clone=<T>(v:T):T=>structuredClone(v);
function random(state:{rngState:number}){let x=state.rngState|0;x^=x<<13;x^=x>>>17;x^=x<<5;state.rngState=x>>>0;return state.rngState/4294967296}
function shuffle<T>(values:T[],state:{rngState:number}){const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(random(state)*(i+1));[a[i],a[j]]=[a[j]!,a[i]!]}return a}
function instance(card:EngineCard,ownerId:string,index:number):CardInstance{return {...card,instanceId:`${ownerId}-${index}-${card.id}`,ownerId,currentAttack:card.attack??0,currentHealth:card.health??0,attacked:false,shield:card.keywords.includes('Shield'),silenced:false,summonedTurn:0}}
function player(id:string,cards:EngineCard[],state:{rngState:number}):PlayerState{const deck=shuffle(cards.map((c,i)=>instance(c,id,i)),state);return{id,leaderHealth:30,maxEnergy:0,energy:0,deck,hand:[],board:{FRONT:[],MIDDLE:[],BACK:[]},graveyard:[]}}
function draw(p:PlayerState,n=1){for(let i=0;i<n;i++){const c=p.deck.shift();if(c&&p.hand.length<7)p.hand.push(c);}}
export function createGame(input:{seed:number;players:[{id:string;deck:EngineCard[]},{id:string;deck:EngineCard[]}]}):GameState{const state={rngState:input.seed>>>0};const p1=player(input.players[0].id,input.players[0].deck,state),p2=player(input.players[1].id,input.players[1].deck,state);draw(p1,5);draw(p2,5);return{seed:input.seed,rngState:state.rngState,turn:0,activePlayerId:p1.id,players:[p1,p2],phase:'MULLIGAN',events:[],effectQueue:[]}}
const getPlayers=(s:GameState,id:string)=>{const me=s.players.find(p=>p.id===id),enemy=s.players.find(p=>p.id!==id);return{me,enemy}};
const units=(p:PlayerState)=>rows.flatMap(r=>p.board[r]);
function startTurn(s:GameState,p:PlayerState){s.turn++;p.maxEnergy=Math.min(10,p.maxEnergy+1);p.energy=p.maxEnergy;if(s.turn>1)draw(p);for(const u of units(p))u.attacked=false;s.events.push({type:'TURN_STARTED',playerId:p.id,message:`Turn ${s.turn}`})}
function finish(s:GameState){for(const p of s.players)if(p.leaderHealth<=0){s.phase='ENDED';const alive=s.players.find(x=>x.leaderHealth>0);s.winnerId=alive?.id??null}}
function damageUnit(s:GameState,target:CardInstance,amount:number){if(target.shield&&!target.silenced){target.shield=false;s.events.push({type:'SHIELD_BROKEN',targetId:target.instanceId,message:'Shield absorbed damage'});return}target.currentHealth-=amount;s.events.push({type:'DAMAGE',targetId:target.instanceId,amount,message:`${amount} damage`});if(target.currentHealth<=0){const owner=s.players.find(p=>p.id===target.ownerId)!;for(const row of rows){const i=owner.board[row].findIndex(x=>x.instanceId===target.instanceId);if(i>=0){owner.graveyard.push(owner.board[row].splice(i,1)[0]!);s.events.push({type:'UNIT_DIED',targetId:target.instanceId,message:'Unit died'});break}}}}
export function applyAction(original:GameState,action:GameAction):Result{const s=clone(original);if(s.phase==='ENDED')return{ok:false,state:original,error:'MATCH_ENDED'};const{me,enemy}=getPlayers(s,action.playerId);if(!me||!enemy)return{ok:false,state:original,error:'PLAYER_NOT_FOUND'};if(action.type==='CONCEDE'){s.phase='ENDED';s.winnerId=enemy.id;return{ok:true,state:s}}if(s.activePlayerId!==action.playerId)return{ok:false,state:original,error:'NOT_YOUR_TURN'};
if(action.type==='MULLIGAN'){if(s.phase!=='MULLIGAN')return{ok:false,state:original,error:'MULLIGAN_CLOSED'};if(action.cardInstanceIds.length>2)return{ok:false,state:original,error:'MULLIGAN_LIMIT'};const chosen=me.hand.filter(c=>action.cardInstanceIds.includes(c.instanceId));if(chosen.length!==action.cardInstanceIds.length)return{ok:false,state:original,error:'CARD_NOT_IN_HAND'};me.hand=me.hand.filter(c=>!action.cardInstanceIds.includes(c.instanceId));me.deck.push(...chosen);me.deck=shuffle(me.deck,s);draw(me,chosen.length);s.phase='MAIN';startTurn(s,me);return{ok:true,state:s}}
if(s.phase==='MULLIGAN'){s.phase='MAIN';startTurn(s,me)}
if(action.type==='PLAY_CARD'){const i=me.hand.findIndex(c=>c.instanceId===action.cardInstanceId),card=me.hand[i];if(!card)return{ok:false,state:original,error:'CARD_NOT_IN_HAND'};if(card.cost>me.energy)return{ok:false,state:original,error:'NOT_ENOUGH_ENERGY'};if(card.type==='UNIT'){if(!action.row||!rows.includes(action.row))return{ok:false,state:original,error:'ROW_REQUIRED'};if(me.board[action.row].length>=3)return{ok:false,state:original,error:'ROW_FULL'};me.energy-=card.cost;me.hand.splice(i,1);card.row=action.row;card.summonedTurn=s.turn;me.board[action.row].push(card);s.events.push({type:'UNIT_SUMMONED',playerId:me.id,sourceId:card.instanceId,message:`${card.name} summoned`})}else{const target=action.targetId?units(enemy).find(x=>x.instanceId===action.targetId):undefined;if(target?.keywords.includes('Ward')&&!target.silenced)return{ok:false,state:original,error:'WARD_BLOCKS'};me.energy-=card.cost;me.hand.splice(i,1);if(target)damageUnit(s,target,card.damage??1);else{enemy.leaderHealth-=card.damage??1;s.events.push({type:'LEADER_DAMAGE',targetId:enemy.id,amount:card.damage??1,message:'Spell damage'})}me.graveyard.push(card)}finish(s);return{ok:true,state:s}}
if(action.type==='ATTACK'){const attacker=units(me).find(x=>x.instanceId===action.attackerId);if(!attacker)return{ok:false,state:original,error:'ATTACKER_NOT_FOUND'};if(attacker.attacked)return{ok:false,state:original,error:'ALREADY_ATTACKED'};if(attacker.summonedTurn===s.turn&&!attacker.keywords.includes('Rush'))return{ok:false,state:original,error:'SUMMONING_SICKNESS'};const taunts=units(enemy).filter(x=>x.keywords.includes('Taunt')&&!x.silenced);if(action.targetId===enemy.id){if(taunts.length)return{ok:false,state:original,error:'TAUNT_BLOCKS'};enemy.leaderHealth-=attacker.currentAttack}else{const target=units(enemy).find(x=>x.instanceId===action.targetId);if(!target)return{ok:false,state:original,error:'TARGET_NOT_FOUND'};if(taunts.length&&!taunts.includes(target))return{ok:false,state:original,error:'TAUNT_BLOCKS'};damageUnit(s,target,attacker.currentAttack);damageUnit(s,attacker,target.currentAttack)}attacker.attacked=true;finish(s);return{ok:true,state:s}}
if(action.type==='END_TURN'){s.activePlayerId=enemy.id;startTurn(s,enemy);return{ok:true,state:s}}return{ok:false,state:original,error:'UNKNOWN_ACTION'}}
export function silence(unit:CardInstance){unit.silenced=true;unit.shield=false;unit.keywords=[]}
export function legalActions(s:GameState,playerId:string):GameAction[]{const p=s.players.find(x=>x.id===playerId);if(!p||s.activePlayerId!==playerId||s.phase==='ENDED')return[];const out:GameAction[]=[{type:'END_TURN',playerId}];for(const c of p.hand.filter(x=>x.cost<=p.energy)){if(c.type==='UNIT')for(const row of rows)if(p.board[row].length<3)out.push({type:'PLAY_CARD',playerId,cardInstanceId:c.instanceId,row});else out.push({type:'PLAY_CARD',playerId,cardInstanceId:c.instanceId})}return out}
