export type Row='FRONT'|'MIDDLE'|'BACK';
export type Keyword='Taunt'|'Shield'|'Rush'|'Silence'|'Ward'|'Foresee'|'Resonance';
export interface EngineCard {id:string;name:string;description?:string;type:'UNIT'|'SPELL';cost:number;attack?:number;health?:number;keywords:Keyword[];damage?:number}
export interface CardInstance extends EngineCard {instanceId:string;ownerId:string;currentAttack:number;currentHealth:number;row?:Row;attacked:boolean;shield:boolean;silenced:boolean;summonedTurn:number}
export interface PlayerState {id:string;leaderHealth:number;maxEnergy:number;energy:number;spellsPlayedThisTurn:number;deck:CardInstance[];hand:CardInstance[];board:Record<Row,CardInstance[]>;graveyard:CardInstance[]}
export interface GameEvent {type:string;playerId?:string;sourceId?:string;targetId?:string;amount?:number;message:string}
export interface GameState {seed:number;rngState:number;turn:number;activePlayerId:string;players:[PlayerState,PlayerState];phase:'MULLIGAN'|'MAIN'|'ENDED';winnerId?:string|null;events:GameEvent[];effectQueue:GameEvent[]}
export type GameAction={type:'MULLIGAN';playerId:string;cardInstanceIds:string[]}|{type:'PLAY_CARD';playerId:string;cardInstanceId:string;row?:Row;targetId?:string}|{type:'ATTACK';playerId:string;attackerId:string;targetId:string}|{type:'END_TURN';playerId:string}|{type:'CONCEDE';playerId:string};
export type Result={ok:true;state:GameState}|{ok:false;state:GameState;error:string};
const rows:Row[]=['FRONT','MIDDLE','BACK'];
const clone=<T>(v:T):T=>structuredClone(v);
function random(state:{rngState:number}){let x=state.rngState|0;x^=x<<13;x^=x>>>17;x^=x<<5;state.rngState=x>>>0;return state.rngState/4294967296}
function shuffle<T>(values:T[],state:{rngState:number}){const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(random(state)*(i+1));[a[i],a[j]]=[a[j]!,a[i]!]}return a}
function instance(card:EngineCard,ownerId:string,index:number):CardInstance{return {...card,instanceId:`${ownerId}-${index}-${card.id}`,ownerId,currentAttack:card.attack??0,currentHealth:card.health??0,attacked:false,shield:card.keywords.includes('Shield'),silenced:false,summonedTurn:0}}
function player(id:string,cards:EngineCard[],state:{rngState:number}):PlayerState{const deck=shuffle(cards.map((c,i)=>instance(c,id,i)),state);return{id,leaderHealth:100,maxEnergy:0,energy:0,spellsPlayedThisTurn:0,deck,hand:[],board:{FRONT:[],MIDDLE:[],BACK:[]},graveyard:[]}}
function draw(p:PlayerState,n=1){for(let i=0;i<n;i++){const c=p.deck.shift();if(c&&p.hand.length<7)p.hand.push(c);}}
export function createGame(input:{seed:number;players:[{id:string;deck:EngineCard[]},{id:string;deck:EngineCard[]}]}):GameState{const state={rngState:input.seed>>>0};const p1=player(input.players[0].id,input.players[0].deck,state),p2=player(input.players[1].id,input.players[1].deck,state);draw(p1,5);draw(p2,5);return{seed:input.seed,rngState:state.rngState,turn:0,activePlayerId:p1.id,players:[p1,p2],phase:'MULLIGAN',events:[],effectQueue:[]}}
const getPlayers=(s:GameState,id:string)=>{const me=s.players.find(p=>p.id===id),enemy=s.players.find(p=>p.id!==id);return{me,enemy}};
const units=(p:PlayerState)=>rows.flatMap(r=>p.board[r]);
const effectText=(card:CardInstance)=>card.description?.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d')??'';
const hasEffect=(card:CardInstance,text:string)=>effectText(card).includes(text);
function healLeader(state:GameState,player:PlayerState,amount:number,source:CardInstance){const before=player.leaderHealth;player.leaderHealth=Math.min(100,player.leaderHealth+amount);const healed=player.leaderHealth-before;if(healed)state.events.push({type:'LEADER_HEALED',playerId:player.id,sourceId:source.instanceId,amount:healed,message:`Leader healed ${healed}`})}
function buffUnit(state:GameState,unit:CardInstance,attack:number,health:number,sourceId=unit.instanceId){unit.currentAttack+=attack;unit.currentHealth+=health;state.events.push({type:'UNIT_BUFFED',playerId:unit.ownerId,sourceId,targetId:unit.instanceId,amount:attack+health,message:`${unit.name} gained +${attack}/+${health}`})}
function applySummonEffects(state:GameState,me:PlayerState,enemy:PlayerState,card:CardInstance){
 if(card.keywords.includes('Foresee')&&me.deck.length>1){const top=me.deck[0]!;if(top.cost>4)me.deck.push(me.deck.shift()!);state.events.push({type:'FORESEE',playerId:me.id,sourceId:card.instanceId,message:top.cost>4?'Foresee moved a card to bottom':'Foresee kept the top card'})}
 if(card.keywords.includes('Resonance')&&me.spellsPlayedThisTurn>0)buffUnit(state,card,1,1);
 if(hasEffect(card,'trieu hoi: nhan +1 cong'))buffUnit(state,card,1,0);
 const teamBuff=hasEffect(card,'toan bo dong minh nhan +3 cong/+3 mau')?3:hasEffect(card,'toan bo dong minh nhan +2 cong va +2 mau')?2:0;
 if(teamBuff)for(const ally of units(me))if(ally.instanceId!==card.instanceId)buffUnit(state,ally,teamBuff,teamBuff,card.instanceId);
 if(hasEffect(card,'dong minh cung hang nhan +1 cong')&&card.row)for(const ally of me.board[card.row])if(ally.instanceId!==card.instanceId)buffUnit(state,ally,1,0,card.instanceId);
 if(card.row)for(const ally of me.board[card.row])if(ally.instanceId!==card.instanceId&&hasEffect(ally,'dong minh cung hang nhan +1 cong'))buffUnit(state,card,1,0,ally.instanceId);
 const summonDamage=hasEffect(card,'co luc: khi trieu hoi, gay 4 sat thuong')?4:hasEffect(card,'trieu hoi: gay 2 sat thuong')?2:0;
 if(summonDamage){const target=[...units(enemy)].sort((a,b)=>a.currentHealth-b.currentHealth)[0];if(target)damageUnit(state,target,summonDamage);else{enemy.leaderHealth-=summonDamage;state.events.push({type:'LEADER_DAMAGE',sourceId:card.instanceId,targetId:enemy.id,amount:summonDamage,message:'Summon damage'})}if(summonDamage===4)draw(me)}
}
function castGrandSpell(state:GameState,me:PlayerState,enemy:PlayerState,card:CardInstance){const targets=[...units(enemy)];if(!targets.length){enemy.leaderHealth-=10;state.events.push({type:'LEADER_DAMAGE',sourceId:card.instanceId,targetId:enemy.id,amount:10,message:'Grand spell damage'})}else{const base=Math.floor(10/targets.length),remainder=10%targets.length;targets.forEach((target,index)=>damageUnit(state,target,base+(index<remainder?1:0)))}draw(me,2)}
function applySpellEffects(state:GameState,me:PlayerState,enemy:PlayerState,card:CardInstance,target:CardInstance|undefined,targetKilled:boolean){me.spellsPlayedThisTurn++;if(target&&targetKilled&&hasEffect(card,'neu muc tieu bi ha, rut 1 la'))draw(me);if(hasEffect(card,'dong minh yeu nhat nhan +1 mau')){const ally=[...units(me)].sort((a,b)=>a.currentHealth-b.currentHealth)[0];if(ally)buffUnit(state,ally,0,1,card.instanceId)}state.events.push({type:'SPELL_CAST',playerId:me.id,sourceId:card.instanceId,targetId:target?.instanceId??enemy.id,message:`${card.name} cast`})}
function applyKillEffects(state:GameState,owner:PlayerState,attacker:CardInstance){if(hasEffect(attacker,'moi lan don vi nay ha guc muc tieu, tang vinh vien +3 cong/+3 mau'))buffUnit(state,attacker,3,3);if(hasEffect(attacker,'khi ha guc muc tieu, hoi 1 mau cho thu linh')||hasEffect(attacker,'ha guc: hoi 2 mau cho thu linh'))healLeader(state,owner,hasEffect(attacker,'hoi 2 mau')?2:1,attacker)}
function applyEndTurnEffects(state:GameState,player:PlayerState){for(const unit of units(player)){if(hasEffect(unit,'cuoi luot: rut 1 la neu con it hon 3 la tren tay')&&player.hand.length<3){draw(player);state.events.push({type:'CARD_DRAWN',playerId:player.id,sourceId:unit.instanceId,message:'End turn draw'})}if(hasEffect(unit,'trieu hoi: nhan +1 cong trong luot nay'))unit.currentAttack=Math.max(0,unit.currentAttack-1)}}
function startTurn(s:GameState,p:PlayerState){s.turn++;p.spellsPlayedThisTurn=0;p.maxEnergy=Math.min(10,p.maxEnergy+1);p.energy=Math.min(20,p.energy+p.maxEnergy);if(s.turn>1)draw(p);for(const u of units(p)){u.attacked=false;if(hasEffect(u,'dau luot: nhan +1 mau toi da'))buffUnit(s,u,0,1)}s.events.push({type:'TURN_STARTED',playerId:p.id,amount:p.energy,message:`Turn ${s.turn} · ${p.energy} energy`})}
function finish(s:GameState){for(const p of s.players)if(p.leaderHealth<=0){s.phase='ENDED';const alive=s.players.find(x=>x.leaderHealth>0);s.winnerId=alive?.id??null;return}if(s.phase==='MAIN'&&s.turn>1&&s.players.some(player=>player.deck.length===0)){const[a,b]=s.players;s.phase='ENDED';s.winnerId=a.leaderHealth===b.leaderHealth?null:a.leaderHealth>b.leaderHealth?a.id:b.id;s.events.push({type:'DECK_EXHAUSTED',message:s.winnerId?`Deck exhausted · ${s.winnerId} wins on health`:'Deck exhausted · draw on equal health'})}}
function damageUnit(s:GameState,target:CardInstance,amount:number){if(target.shield&&!target.silenced){target.shield=false;s.events.push({type:'SHIELD_BROKEN',targetId:target.instanceId,message:'Shield absorbed damage'});return false}target.currentHealth-=amount;s.events.push({type:'DAMAGE',targetId:target.instanceId,amount,message:`${amount} damage`});if(target.currentHealth<=0){const owner=s.players.find(p=>p.id===target.ownerId)!;for(const row of rows){const i=owner.board[row].findIndex(x=>x.instanceId===target.instanceId);if(i>=0){owner.graveyard.push(owner.board[row].splice(i,1)[0]!);s.events.push({type:'UNIT_DIED',targetId:target.instanceId,message:'Unit died'});break}}return true}return false}
export function applyAction(original:GameState,action:GameAction):Result{const s=clone(original);if(s.phase==='ENDED')return{ok:false,state:original,error:'MATCH_ENDED'};const{me,enemy}=getPlayers(s,action.playerId);if(!me||!enemy)return{ok:false,state:original,error:'PLAYER_NOT_FOUND'};if(action.type==='CONCEDE'){s.phase='ENDED';s.winnerId=enemy.id;return{ok:true,state:s}}if(s.activePlayerId!==action.playerId)return{ok:false,state:original,error:'NOT_YOUR_TURN'};
if(action.type==='MULLIGAN'){if(s.phase!=='MULLIGAN')return{ok:false,state:original,error:'MULLIGAN_CLOSED'};if(action.cardInstanceIds.length>2)return{ok:false,state:original,error:'MULLIGAN_LIMIT'};const chosen=me.hand.filter(c=>action.cardInstanceIds.includes(c.instanceId));if(chosen.length!==action.cardInstanceIds.length)return{ok:false,state:original,error:'CARD_NOT_IN_HAND'};me.hand=me.hand.filter(c=>!action.cardInstanceIds.includes(c.instanceId));me.deck.push(...chosen);me.deck=shuffle(me.deck,s);draw(me,chosen.length);s.phase='MAIN';startTurn(s,me);return{ok:true,state:s}}
if(s.phase==='MULLIGAN'){s.phase='MAIN';startTurn(s,me)}
if(action.type==='PLAY_CARD'){const i=me.hand.findIndex(c=>c.instanceId===action.cardInstanceId),card=me.hand[i];if(!card)return{ok:false,state:original,error:'CARD_NOT_IN_HAND'};if(card.cost>me.energy)return{ok:false,state:original,error:'NOT_ENOUGH_ENERGY'};if(card.type==='UNIT'){if(!action.row||!rows.includes(action.row))return{ok:false,state:original,error:'ROW_REQUIRED'};if(me.board[action.row].length>=3)return{ok:false,state:original,error:'ROW_FULL'};me.energy-=card.cost;me.hand.splice(i,1);card.row=action.row;card.summonedTurn=s.turn;me.board[action.row].push(card);applySummonEffects(s,me,enemy,card);s.events.push({type:'UNIT_SUMMONED',playerId:me.id,sourceId:card.instanceId,message:`${card.name} summoned`})}else{const target=action.targetId?units(enemy).find(x=>x.instanceId===action.targetId):undefined;if(target?.keywords.includes('Ward')&&!target.silenced)return{ok:false,state:original,error:'WARD_BLOCKS'};me.energy-=card.cost;me.hand.splice(i,1);const grandSpell=hasEffect(card,'dai phep: gay 10 sat thuong chia deu cho moi ke dich');const targetKilled=grandSpell?(castGrandSpell(s,me,enemy,card),false):target?damageUnit(s,target,card.damage??1):false;if(!target&&!grandSpell){enemy.leaderHealth-=card.damage??1;s.events.push({type:'LEADER_DAMAGE',targetId:enemy.id,amount:card.damage??1,message:'Spell damage'})}applySpellEffects(s,me,enemy,card,target,targetKilled);me.graveyard.push(card)}finish(s);return{ok:true,state:s}}
if(action.type==='ATTACK'){const attacker=units(me).find(x=>x.instanceId===action.attackerId);if(!attacker)return{ok:false,state:original,error:'ATTACKER_NOT_FOUND'};if(attacker.attacked)return{ok:false,state:original,error:'ALREADY_ATTACKED'};if(attacker.summonedTurn===s.turn&&!attacker.keywords.includes('Rush'))return{ok:false,state:original,error:'SUMMONING_SICKNESS'};const taunts=units(enemy).filter(x=>x.keywords.includes('Taunt')&&!x.silenced);if(action.targetId===enemy.id){if(taunts.length)return{ok:false,state:original,error:'TAUNT_BLOCKS'};enemy.leaderHealth-=attacker.currentAttack;s.events.push({type:'LEADER_DAMAGE',playerId:me.id,sourceId:attacker.instanceId,targetId:enemy.id,amount:attacker.currentAttack,message:`${attacker.name} dealt ${attacker.currentAttack} leader damage`})}else{const target=units(enemy).find(x=>x.instanceId===action.targetId);if(!target)return{ok:false,state:original,error:'TARGET_NOT_FOUND'};if(taunts.length&&!taunts.includes(target))return{ok:false,state:original,error:'TAUNT_BLOCKS'};const targetKilled=damageUnit(s,target,attacker.currentAttack);const attackerKilled=damageUnit(s,attacker,target.currentAttack);if(hasEffect(target,'khi bi danh: gay lai 1 sat thuong cho ke tan cong'))damageUnit(s,attacker,1);if(targetKilled&&!attackerKilled&&units(me).includes(attacker))applyKillEffects(s,me,attacker);if(!attackerKilled&&units(me).includes(attacker)&&hasEffect(attacker,'neu song sot giao tranh, nhan +1 mau'))buffUnit(s,attacker,0,1)}attacker.attacked=true;finish(s);return{ok:true,state:s}}
if(action.type==='END_TURN'){applyEndTurnEffects(s,me);s.activePlayerId=enemy.id;startTurn(s,enemy);finish(s);return{ok:true,state:s}}return{ok:false,state:original,error:'UNKNOWN_ACTION'}}
export function silence(unit:CardInstance){unit.silenced=true;unit.shield=false;unit.keywords=[]}
export function legalActions(s:GameState,playerId:string):GameAction[]{const p=s.players.find(x=>x.id===playerId);if(!p||s.activePlayerId!==playerId||s.phase==='ENDED')return[];const out:GameAction[]=[{type:'END_TURN',playerId}];for(const c of p.hand.filter(x=>x.cost<=p.energy)){if(c.type==='UNIT')for(const row of rows)if(p.board[row].length<3)out.push({type:'PLAY_CARD',playerId,cardInstanceId:c.instanceId,row});else out.push({type:'PLAY_CARD',playerId,cardInstanceId:c.instanceId})}return out}
