export type Row='FRONT'|'MIDDLE'|'BACK';
export type Keyword='Taunt'|'Shield'|'Rush'|'Silence'|'Ward'|'Foresee'|'Resonance';
export interface EngineCard {id:string;name:string;description?:string;type:'UNIT'|'SPELL';cost:number;attack?:number;health?:number;keywords:Keyword[];damage?:number}
export interface CardInstance extends EngineCard {instanceId:string;ownerId:string;currentAttack:number;currentHealth:number;row?:Row;attacked:boolean;shield:boolean;silenced:boolean;summonedTurn:number}
export interface PlayerState {id:string;leaderHealth:number;maxEnergy:number;energy:number;spellsPlayedThisTurn:number;deck:CardInstance[];hand:CardInstance[];board:Record<Row,CardInstance[]>;graveyard:CardInstance[]}
export interface GameEvent {type:string;playerId?:string;sourceId?:string;targetId?:string;amount?:number;message:string}
export interface GameState {seed:number;rngState:number;turn:number;activePlayerId:string;players:[PlayerState,PlayerState];phase:'MULLIGAN'|'MAIN'|'ENDED';winnerId?:string|null;events:GameEvent[];effectQueue:GameEvent[];pendingForesee?:{playerId:string;sourceId:string;cardInstanceId:string}}
export type GameAction={type:'MULLIGAN';playerId:string;cardInstanceIds:string[]}|{type:'PLAY_CARD';playerId:string;cardInstanceId:string;row?:Row;targetId?:string}|{type:'RESOLVE_FORESEE';playerId:string;choice:'KEEP'|'BOTTOM'}|{type:'ATTACK';playerId:string;attackerId:string;targetId:string}|{type:'END_TURN';playerId:string}|{type:'CONCEDE';playerId:string};
export type Result={ok:true;state:GameState}|{ok:false;state:GameState;error:string};
const rows:Row[]=['FRONT','MIDDLE','BACK'];
const clone=<T>(v:T):T=>structuredClone(v);
function random(state:{rngState:number}){let x=state.rngState|0;x^=x<<13;x^=x>>>17;x^=x<<5;state.rngState=x>>>0;return state.rngState/4294967296}
function shuffle<T>(values:T[],state:{rngState:number}){const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(random(state)*(i+1));[a[i],a[j]]=[a[j]!,a[i]!]}return a}
function instance(card:EngineCard,ownerId:string,index:number):CardInstance{return {...card,instanceId:`${ownerId}-${index}-${card.id}`,ownerId,currentAttack:card.attack??0,currentHealth:card.health??0,attacked:false,shield:card.keywords.includes('Shield'),silenced:false,summonedTurn:0}}
function player(id:string,cards:EngineCard[],state:{rngState:number}):PlayerState{const deck=shuffle(cards.map((c,i)=>instance(c,id,i)),state);return{id,leaderHealth:100,maxEnergy:0,energy:0,spellsPlayedThisTurn:0,deck,hand:[],board:{FRONT:[],MIDDLE:[],BACK:[]},graveyard:[]}}
function draw(p:PlayerState,n=1){for(let i=0;i<n;i++){const c=p.deck.shift();if(c)p.hand.push(c);}}
export function createGame(input:{seed:number;players:[{id:string;deck:EngineCard[]},{id:string;deck:EngineCard[]}]}):GameState{const state={rngState:input.seed>>>0};const p1=player(input.players[0].id,input.players[0].deck,state),p2=player(input.players[1].id,input.players[1].deck,state);draw(p1,5);draw(p2,5);return{seed:input.seed,rngState:state.rngState,turn:0,activePlayerId:p1.id,players:[p1,p2],phase:'MULLIGAN',events:[],effectQueue:[]}}
const getPlayers=(s:GameState,id:string)=>{const me=s.players.find(p=>p.id===id),enemy=s.players.find(p=>p.id!==id);return{me,enemy}};
const units=(p:PlayerState)=>rows.flatMap(r=>p.board[r]);
const effectText=(card:CardInstance)=>card.description?.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d')??'';
const hasEffect=(card:CardInstance,text:string)=>effectText(card).includes(text);
function healLeader(state:GameState,player:PlayerState,amount:number,source:CardInstance){const before=player.leaderHealth;player.leaderHealth=Math.min(100,player.leaderHealth+amount);const healed=player.leaderHealth-before;if(healed)state.events.push({type:'LEADER_HEALED',playerId:player.id,sourceId:source.instanceId,amount:healed,message:`Leader healed ${healed}`})}
function buffUnit(state:GameState,unit:CardInstance,attack:number,health:number,sourceId=unit.instanceId){unit.currentAttack+=attack;unit.currentHealth+=health;state.events.push({type:'UNIT_BUFFED',playerId:unit.ownerId,sourceId,targetId:unit.instanceId,amount:attack+health,message:`${unit.name} gained +${attack}/+${health}`})}
function applySummonEffects(state:GameState,me:PlayerState,enemy:PlayerState,card:CardInstance){
 if(card.keywords.includes('Foresee')&&me.deck.length){const top=me.deck[0]!;state.pendingForesee={playerId:me.id,sourceId:card.instanceId,cardInstanceId:top.instanceId};state.events.push({type:'FORESEE_REVEALED',playerId:me.id,sourceId:card.instanceId,targetId:top.instanceId,message:`Foresee revealed ${top.name}`})}
 if(card.keywords.includes('Resonance')&&me.spellsPlayedThisTurn>0)buffUnit(state,card,1,1);
 if(hasEffect(card,'trieu hoi: nhan +1 cong'))buffUnit(state,card,1,0);
 if(hasEffect(card,'trieu hoi: nhan 2 nang luong')){me.energy=Math.min(20,me.energy+2);state.events.push({type:'ENERGY_GAINED',playerId:me.id,sourceId:card.instanceId,amount:2,message:'Gained 2 energy'})}
 if(hasEffect(card,'trieu hoi: tieu toi da 2 nang luong con lai')){const spent=Math.min(2,me.energy);me.energy-=spent;if(spent)buffUnit(state,card,spent,spent)}
 const teamBuff=hasEffect(card,'toan bo dong minh nhan +4 cong va +4 mau')?4:hasEffect(card,'toan bo dong minh nhan +3 cong/+3 mau')?3:hasEffect(card,'toan bo dong minh nhan +2 cong va +2 mau')?2:0;
 if(teamBuff)for(const ally of units(me))if(ally.instanceId!==card.instanceId)buffUnit(state,ally,teamBuff,teamBuff,card.instanceId);
 if(hasEffect(card,'thu linh hoi 4 mau'))healLeader(state,me,4,card);
 if(hasEffect(card,'dong minh cung hang nhan +1 cong')&&card.row)for(const ally of me.board[card.row])if(ally.instanceId!==card.instanceId)buffUnit(state,ally,1,0,card.instanceId);
 if(card.row)for(const ally of me.board[card.row])if(ally.instanceId!==card.instanceId&&hasEffect(ally,'dong minh cung hang nhan +1 cong'))buffUnit(state,card,1,0,ally.instanceId);
 const summonDamage=hasEffect(card,'trieu hoi: gay 7 sat thuong')?7:hasEffect(card,'co luc: khi trieu hoi, gay 4 sat thuong')?4:hasEffect(card,'trieu hoi: gay 2 sat thuong')?2:0;
 if(summonDamage){const target=[...units(enemy)].sort((a,b)=>a.currentHealth-b.currentHealth)[0];if(target)damageUnit(state,target,summonDamage);else{enemy.leaderHealth-=summonDamage;state.events.push({type:'LEADER_DAMAGE',sourceId:card.instanceId,targetId:enemy.id,amount:summonDamage,message:'Summon damage'})}if(summonDamage===4)draw(me)}
 if(hasEffect(card,'toan bo dong minh nhan +3 cong/+5 mau')){for(const ally of units(me)){if(ally.instanceId!==card.instanceId)buffUnit(state,ally,3,5,card.instanceId);ally.shield=true;if(!ally.keywords.includes('Shield'))ally.keywords.push('Shield')}healLeader(state,me,5,card)}
 if(hasEffect(card,'danh cap 4 cong')){const target=[...units(enemy)].sort((a,b)=>b.currentAttack-a.currentAttack)[0];if(target){const stolen=Math.min(4,target.currentAttack);target.currentAttack-=stolen;buffUnit(state,card,stolen,0,card.instanceId);state.events.push({type:'ATTACK_STOLEN',playerId:me.id,sourceId:card.instanceId,targetId:target.instanceId,amount:stolen,message:`${card.name} stole ${stolen} attack from ${target.name}`})}else{draw(me,2);state.events.push({type:'CARD_DRAWN',playerId:me.id,sourceId:card.instanceId,amount:2,message:'No enemy · drew 2 cards'})}}
 if(hasEffect(card,'trieu hoi: rut 2 la va nhan 4 nang luong')){draw(me,2);me.energy=Math.min(20,me.energy+4);state.events.push({type:'ARCANE_SURGE',playerId:me.id,sourceId:card.instanceId,amount:4,message:'Drew 2 cards and gained 4 energy'})}
 if(hasEffect(card,'dat mau hai thu linh bang trung binh hien tai')){const average=Math.floor((me.leaderHealth+enemy.leaderHealth)/2);me.leaderHealth=average;enemy.leaderHealth=average;state.events.push({type:'BALANCE_RESTORED',playerId:me.id,sourceId:card.instanceId,amount:average,message:`Both leaders balanced at ${average} health`})}
 if(hasEffect(card,'trieu hoi lai dong minh manh nhat tu nghia dia')){const candidates=me.graveyard.filter(unit=>unit.type==='UNIT').sort((a,b)=>(b.currentAttack+b.currentHealth)-(a.currentAttack+a.currentHealth));const revived=candidates[0];if(revived){const index=me.graveyard.findIndex(unit=>unit.instanceId===revived.instanceId),row=rows.find(candidate=>me.board[candidate].length<3);if(index>=0&&row){me.graveyard.splice(index,1);revived.currentHealth=1;revived.attacked=false;revived.summonedTurn=state.turn;revived.row=row;me.board[row].push(revived);state.events.push({type:'UNIT_REVIVED',playerId:me.id,sourceId:card.instanceId,targetId:revived.instanceId,message:`${revived.name} revived with 1 health`})}}}
}
function castGrandSpell(state:GameState,me:PlayerState,enemy:PlayerState,card:CardInstance){const text=effectText(card),damage=Number(text.match(/dai phep: gay (\d+) sat thuong/)?.[1]??10),cards=Number(text.match(/sau do rut (\d+) la/)?.[1]??2),energy=Number(text.match(/nhan (\d+) nang luong/)?.[1]??0),leaderDamage=Number(text.match(/va (\d+) sat thuong len thu linh/)?.[1]??0),targets=[...units(enemy)];if(!targets.length){enemy.leaderHealth-=damage;state.events.push({type:'LEADER_DAMAGE',sourceId:card.instanceId,targetId:enemy.id,amount:damage,message:'Grand spell damage'})}else{const base=Math.floor(damage/targets.length),remainder=damage%targets.length;targets.forEach((target,index)=>damageUnit(state,target,base+(index<remainder?1:0)))}if(leaderDamage){enemy.leaderHealth-=leaderDamage;state.events.push({type:'LEADER_DAMAGE',sourceId:card.instanceId,targetId:enemy.id,amount:leaderDamage,message:`Grand spell dealt ${leaderDamage} leader damage`})}draw(me,cards);if(energy){me.energy=Math.min(20,me.energy+energy);state.events.push({type:'ENERGY_GAINED',playerId:me.id,sourceId:card.instanceId,amount:energy,message:`Gained ${energy} energy`})}}
function applySpellEffects(state:GameState,me:PlayerState,enemy:PlayerState,card:CardInstance,target:CardInstance|undefined,targetKilled:boolean){const grand=hasEffect(card,'dai phep:');me.spellsPlayedThisTurn++;if(target&&targetKilled&&hasEffect(card,'neu muc tieu bi ha, rut 1 la'))draw(me);if(target&&targetKilled&&hasEffect(card,'neu ha guc, rut 3 la, nhan 2 nang luong va hoi 15 mau')){draw(me,3);me.energy=Math.min(20,me.energy+2);healLeader(state,me,15,card);state.events.push({type:'ENERGY_GAINED',playerId:me.id,sourceId:card.instanceId,amount:2,message:'Origin Shard execution gained 2 energy'})}else if(target&&targetKilled&&hasEffect(card,'neu ha guc, rut 2 la va hoi 10 mau')){draw(me,2);healLeader(state,me,10,card)}if(hasEffect(card,'toan bo dong minh nhan khien chan, +4 cong va +12 mau')){for(const ally of units(me)){buffUnit(state,ally,4,12,card.instanceId);ally.shield=true;if(!ally.keywords.includes('Shield'))ally.keywords.push('Shield')}healLeader(state,me,15,card)}else if(hasEffect(card,'toan bo dong minh nhan khien chan va +8 mau')){for(const ally of units(me)){buffUnit(state,ally,0,8,card.instanceId);ally.shield=true;if(!ally.keywords.includes('Shield'))ally.keywords.push('Shield')}healLeader(state,me,8,card)}else if(hasEffect(card,'hoi 8 mau cho thu linh'))healLeader(state,me,8,card);if(!grand&&hasEffect(card,'rut 3 la')&&!hasEffect(card,'neu ha guc')){draw(me,3);state.events.push({type:'CARD_DRAWN',playerId:me.id,sourceId:card.instanceId,amount:3,message:'Drew 3 cards'})}if(!grand&&hasEffect(card,'nhan 3 nang luong')){me.energy=Math.min(20,me.energy+3);state.events.push({type:'ENERGY_GAINED',playerId:me.id,sourceId:card.instanceId,amount:3,message:'Gained 3 energy'})}if(hasEffect(card,'dong minh yeu nhat nhan +1 mau')){const ally=[...units(me)].sort((a,b)=>a.currentHealth-b.currentHealth)[0];if(ally)buffUnit(state,ally,0,1,card.instanceId)}state.events.push({type:'SPELL_CAST',playerId:me.id,sourceId:card.instanceId,targetId:target?.instanceId??enemy.id,message:`${card.name} cast`})}
function applyKillEffects(state:GameState,owner:PlayerState,attacker:CardInstance){if(hasEffect(attacker,'ha guc: nhan vinh vien +6 cong/+4 mau')){buffUnit(state,attacker,6,4);owner.energy=Math.min(20,owner.energy+3);healLeader(state,owner,3,attacker);state.events.push({type:'ENERGY_GAINED',playerId:owner.id,sourceId:attacker.instanceId,amount:3,message:'Eclipse kill refunded 3 energy'})}else if(hasEffect(attacker,'moi lan don vi nay ha guc muc tieu, tang vinh vien +5 cong/+5 mau')){buffUnit(state,attacker,5,5);healLeader(state,owner,3,attacker)}else if(hasEffect(attacker,'moi lan don vi nay ha guc muc tieu, tang vinh vien +3 cong/+3 mau'))buffUnit(state,attacker,3,3);if(hasEffect(attacker,'ha guc: hoan lai 2 nang luong')){owner.energy=Math.min(20,owner.energy+2);state.events.push({type:'ENERGY_GAINED',playerId:owner.id,sourceId:attacker.instanceId,amount:2,message:'Kill refunded 2 energy'})}if(hasEffect(attacker,'khi ha guc muc tieu, hoi 1 mau cho thu linh')||hasEffect(attacker,'ha guc: hoi 2 mau cho thu linh'))healLeader(state,owner,hasEffect(attacker,'hoi 2 mau')?2:1,attacker)}
function applyEndTurnEffects(state:GameState,player:PlayerState){for(const unit of units(player)){if(hasEffect(unit,'cuoi luot: rut 1 la neu con it hon 3 la tren tay')&&player.hand.length<3){draw(player);state.events.push({type:'CARD_DRAWN',playerId:player.id,sourceId:unit.instanceId,message:'End turn draw'})}if(hasEffect(unit,'cuoi luot: neu con it nhat 3 nang luong, nhan khien chan')&&player.energy>=3){unit.shield=true;if(!unit.keywords.includes('Shield'))unit.keywords.push('Shield');state.events.push({type:'SHIELD_GAINED',playerId:player.id,sourceId:unit.instanceId,message:'Reserve shield gained'})}if(hasEffect(unit,'cuoi luot: neu con it nhat 5 nang luong, nhan +2 cong/+2 mau')&&player.energy>=5)buffUnit(state,unit,2,2);if(hasEffect(unit,'cuoi luot: neu da dung phep, nhan +3 cong/+3 mau')&&player.spellsPlayedThisTurn>0)buffUnit(state,unit,3,3);if(hasEffect(unit,'trieu hoi: nhan +1 cong trong luot nay'))unit.currentAttack=Math.max(0,unit.currentAttack-1)}}
function startTurn(s:GameState,p:PlayerState){s.turn++;p.spellsPlayedThisTurn=0;p.maxEnergy=Math.min(10,p.maxEnergy+1);p.energy=Math.min(20,p.energy+p.maxEnergy);if(s.turn>1)draw(p);for(const u of units(p)){u.attacked=false;if(hasEffect(u,'dau luot: nhan +1 mau toi da'))buffUnit(s,u,0,1)}s.events.push({type:'TURN_STARTED',playerId:p.id,amount:p.energy,message:`Turn ${s.turn} · ${p.energy} energy`})}
function finish(s:GameState){for(const p of s.players)if(p.leaderHealth<=0){s.phase='ENDED';const alive=s.players.find(x=>x.leaderHealth>0);s.winnerId=alive?.id??null;return}if(s.phase==='MAIN'&&s.turn>1&&s.players.some(player=>player.deck.length===0)){const[a,b]=s.players;s.phase='ENDED';s.winnerId=a.leaderHealth===b.leaderHealth?null:a.leaderHealth>b.leaderHealth?a.id:b.id;s.events.push({type:'DECK_EXHAUSTED',message:s.winnerId?`Deck exhausted · ${s.winnerId} wins on health`:'Deck exhausted · draw on equal health'})}}
function damageUnit(s:GameState,target:CardInstance,amount:number){if(target.shield&&!target.silenced){target.shield=false;s.events.push({type:'SHIELD_BROKEN',targetId:target.instanceId,message:'Shield absorbed damage'});return false}target.currentHealth-=amount;s.events.push({type:'DAMAGE',targetId:target.instanceId,amount,message:`${amount} damage`});if(target.currentHealth<=0){const owner=s.players.find(p=>p.id===target.ownerId)!;for(const row of rows){const i=owner.board[row].findIndex(x=>x.instanceId===target.instanceId);if(i>=0){owner.graveyard.push(owner.board[row].splice(i,1)[0]!);s.events.push({type:'UNIT_DIED',targetId:target.instanceId,message:'Unit died'});break}}return true}return false}
export function applyAction(original:GameState,action:GameAction):Result{const s=clone(original);if(s.phase==='ENDED')return{ok:false,state:original,error:'MATCH_ENDED'};const{me,enemy}=getPlayers(s,action.playerId);if(!me||!enemy)return{ok:false,state:original,error:'PLAYER_NOT_FOUND'};if(action.type==='CONCEDE'){s.phase='ENDED';s.winnerId=enemy.id;return{ok:true,state:s}}if(s.activePlayerId!==action.playerId)return{ok:false,state:original,error:'NOT_YOUR_TURN'};
if(action.type==='MULLIGAN'){if(s.phase!=='MULLIGAN')return{ok:false,state:original,error:'MULLIGAN_CLOSED'};if(action.cardInstanceIds.length>2)return{ok:false,state:original,error:'MULLIGAN_LIMIT'};const chosen=me.hand.filter(c=>action.cardInstanceIds.includes(c.instanceId));if(chosen.length!==action.cardInstanceIds.length)return{ok:false,state:original,error:'CARD_NOT_IN_HAND'};me.hand=me.hand.filter(c=>!action.cardInstanceIds.includes(c.instanceId));me.deck.push(...chosen);me.deck=shuffle(me.deck,s);draw(me,chosen.length);s.phase='MAIN';startTurn(s,me);return{ok:true,state:s}}
if(s.phase==='MULLIGAN'){s.phase='MAIN';startTurn(s,me)}
if(s.pendingForesee){if(action.type!=='RESOLVE_FORESEE'||action.playerId!==s.pendingForesee.playerId)return{ok:false,state:original,error:'FORESEE_PENDING'};const top=me.deck[0];if(!top||top.instanceId!==s.pendingForesee.cardInstanceId)return{ok:false,state:original,error:'FORESEE_CARD_MISSING'};if(action.choice==='BOTTOM')me.deck.push(me.deck.shift()!);s.events.push({type:'FORESEE_RESOLVED',playerId:me.id,sourceId:s.pendingForesee.sourceId,targetId:top.instanceId,message:action.choice==='BOTTOM'?`${top.name} moved to bottom`:`${top.name} kept on top`});delete s.pendingForesee;return{ok:true,state:s}}
if(action.type==='PLAY_CARD'){const i=me.hand.findIndex(c=>c.instanceId===action.cardInstanceId),card=me.hand[i];if(!card)return{ok:false,state:original,error:'CARD_NOT_IN_HAND'};if(card.cost>me.energy)return{ok:false,state:original,error:'NOT_ENOUGH_ENERGY'};if(card.type==='UNIT'){if(!action.row||!rows.includes(action.row))return{ok:false,state:original,error:'ROW_REQUIRED'};if(me.board[action.row].length>=3)return{ok:false,state:original,error:'ROW_FULL'};me.energy-=card.cost;me.hand.splice(i,1);card.row=action.row;card.summonedTurn=s.turn;me.board[action.row].push(card);applySummonEffects(s,me,enemy,card);s.events.push({type:'UNIT_SUMMONED',playerId:me.id,sourceId:card.instanceId,message:`${card.name} summoned`})}else{const target=action.targetId?units(enemy).find(x=>x.instanceId===action.targetId):undefined;if(target?.keywords.includes('Ward')&&!target.silenced)return{ok:false,state:original,error:'WARD_BLOCKS'};const execute=hasEffect(card,'tieu diet mot don vi co chi phi tu 3 tro xuong');if(execute&&(!target||target.cost>3))return{ok:false,state:original,error:'TARGET_TOO_STRONG'};me.energy-=card.cost;me.hand.splice(i,1);const grandSpell=hasEffect(card,'dai phep:'),utility=hasEffect(card,'hoi 8 mau cho thu linh')||(hasEffect(card,'rut 3 la')&&!hasEffect(card,'neu ha guc'))||hasEffect(card,'nhan 3 nang luong')||hasEffect(card,'toan bo dong minh nhan khien chan va +8 mau')||hasEffect(card,'toan bo dong minh nhan khien chan, +4 cong va +12 mau');const targetKilled=grandSpell?(castGrandSpell(s,me,enemy,card),false):utility?false:target?damageUnit(s,target,execute?target.currentHealth+99:card.damage??1):false;if(!target&&!grandSpell&&!utility){enemy.leaderHealth-=card.damage??1;s.events.push({type:'LEADER_DAMAGE',targetId:enemy.id,amount:card.damage??1,message:'Spell damage'})}applySpellEffects(s,me,enemy,card,target,targetKilled);me.graveyard.push(card)}finish(s);return{ok:true,state:s}}
if(action.type==='ATTACK'){const attacker=units(me).find(x=>x.instanceId===action.attackerId);if(!attacker)return{ok:false,state:original,error:'ATTACKER_NOT_FOUND'};if(attacker.attacked)return{ok:false,state:original,error:'ALREADY_ATTACKED'};if(attacker.summonedTurn===s.turn&&!attacker.keywords.includes('Rush'))return{ok:false,state:original,error:'SUMMONING_SICKNESS'};const defenders=units(enemy),taunts=defenders.filter(x=>x.keywords.includes('Taunt')&&!x.silenced);if(action.targetId===enemy.id){if(defenders.length)return{ok:false,state:original,error:'BOARD_BLOCKS'};enemy.leaderHealth-=attacker.currentAttack;s.events.push({type:'LEADER_DAMAGE',playerId:me.id,sourceId:attacker.instanceId,targetId:enemy.id,amount:attacker.currentAttack,message:`${attacker.name} dealt ${attacker.currentAttack} leader damage`})}else{const target=defenders.find(x=>x.instanceId===action.targetId);if(!target)return{ok:false,state:original,error:'TARGET_NOT_FOUND'};if(taunts.length&&!taunts.includes(target))return{ok:false,state:original,error:'TAUNT_BLOCKS'};const targetKilled=damageUnit(s,target,attacker.currentAttack);const attackerKilled=damageUnit(s,attacker,target.currentAttack);if(hasEffect(target,'khi bi danh: gay lai 1 sat thuong cho ke tan cong'))damageUnit(s,attacker,1);if(targetKilled&&!attackerKilled&&units(me).includes(attacker))applyKillEffects(s,me,attacker);if(!attackerKilled&&units(me).includes(attacker)){if(hasEffect(attacker,'neu song sot giao tranh, nhan +2 cong'))buffUnit(s,attacker,2,0);else if(hasEffect(attacker,'neu song sot giao tranh, nhan +1 mau'))buffUnit(s,attacker,0,1)}}attacker.attacked=true;finish(s);return{ok:true,state:s}}
if(action.type==='END_TURN'){applyEndTurnEffects(s,me);s.activePlayerId=enemy.id;startTurn(s,enemy);finish(s);return{ok:true,state:s}}return{ok:false,state:original,error:'UNKNOWN_ACTION'}}
export function silence(unit:CardInstance){unit.silenced=true;unit.shield=false;unit.keywords=[]}
export function legalActions(s:GameState,playerId:string):GameAction[]{const p=s.players.find(x=>x.id===playerId);if(!p||s.activePlayerId!==playerId||s.phase==='ENDED')return[];if(s.pendingForesee?.playerId===playerId)return[{type:'RESOLVE_FORESEE',playerId,choice:'KEEP'},{type:'RESOLVE_FORESEE',playerId,choice:'BOTTOM'}];const out:GameAction[]=[{type:'END_TURN',playerId}];for(const c of p.hand.filter(x=>x.cost<=p.energy)){if(c.type==='UNIT')for(const row of rows)if(p.board[row].length<3)out.push({type:'PLAY_CARD',playerId,cardInstanceId:c.instanceId,row});else out.push({type:'PLAY_CARD',playerId,cardInstanceId:c.instanceId})}return out}
