import {PrismaClient} from '@prisma/client';import {cards} from '@chronicle/card-data';import {packRates} from'../src/pack-logic.js';import argon2 from'argon2';
const db=new PrismaClient();
const testPassword=await argon2.hash('Test12345!');const testUser=await db.user.upsert({where:{email:'test@chronicle.local'},update:{passwordHash:testPassword},create:{email:'test@chronicle.local',passwordHash:testPassword,profile:{create:{displayName:'Keeper Thử Nghiệm'}}}});for(const code of ['GOLD','DUST','GEM'] as const)await db.userCurrency.upsert({where:{userId_code:{userId:testUser.id,code}},update:{balance:2_000_000_000},create:{userId:testUser.id,code,balance:2_000_000_000}});
const set=await db.cardSet.upsert({where:{code:'CORE'},update:{},create:{code:'CORE',name:'Chronicle Rift Core'}});
for(const card of cards)await db.card.upsert({where:{code:card.code},update:{...card,printLimit:card.printLimit??null,keywords:card.keywords,setId:set.id},create:{...card,keywords:card.keywords,setId:set.id}});
for(const user of [testUser]){for(const faction of ['IRONVALE','ARCANUM'] as const){const selected=await db.card.findMany({where:{faction,collectible:true,rarity:{not:'LIMITED'}},orderBy:{code:'asc'},take:15});await Promise.all(selected.map(card=>db.userCard.upsert({where:{userId_cardId:{userId:user.id,cardId:card.id}},update:{quantity:{set:2}},create:{userId:user.id,cardId:card.id,quantity:2}})));const deck=await db.deck.findFirst({where:{userId:user.id,faction,OR:[{isDefault:true},{name:{endsWith:'Starter'}},{name:{startsWith:'Bộ khởi đầu'}}]}});if(deck){await db.deckCard.deleteMany({where:{deckId:deck.id}});await db.deckCard.createMany({data:selected.map((card,i)=>({deckId:deck.id,cardId:card.id,quantity:2,position:i}))});}}}
const chapter=await db.campaignChapter.upsert({where:{number:1},update:{name:'Người Giữ Ký Ức',description:'Khởi đầu hành trình đóng các khe nứt.'},create:{number:1,name:'Người Giữ Ký Ức',description:'Khởi đầu hành trình đóng các khe nứt.'}});
for(let number=1;number<=11;number++)await db.campaignStage.upsert({where:{chapterId_number:{chapterId:chapter.id,number}},update:{},create:{chapterId:chapter.id,number,name:number===11?'Kẻ Canh Cổng Vỡ':`Khe Nứt ${number}`,kind:number===11?'BOSS':'NORMAL',aiLevel:number<=3?'EASY':number===11?'BOSS':'NORMAL',enemyDeck:{faction:number%2?'IRONVALE':'ARCANUM',codes:cards.filter(c=>c.faction===(number%2?'IRONVALE':'ARCANUM')).slice(0,10).map(c=>c.code)},rewardGold:number===11?1000:100+number*20,rewardDust:number===11?200:0,bossPhases:number===11?[{phase:1,health:30,passive:'Gate Shield'},{phase:2,health:20,passive:'Rift Fury',attackBonus:2}]:undefined}});
for(const p of [{code:'BASIC',name:'Gói Ký Ức Cơ Bản',priceGold:500,faction:null},{code:'IRONVALE',name:'Gói Thành Trì Ironvale',priceGold:600,faction:'IRONVALE' as const},{code:'ARCANUM',name:'Gói Bí Thuật Arcanum',priceGold:600,faction:'ARCANUM' as const},{code:'STARTER',name:'Gói Tân Thủ',priceGold:300,faction:null},{code:'RIFT_SEAL',name:'Ấn Phong Khe Nứt',priceGold:2500,faction:null}]){const pack=await db.pack.upsert({where:{code:p.code},update:p,create:p}),weights=packRates[p.code as keyof typeof packRates];for(let position=0;position<5;position++)await db.packSlot.upsert({where:{packId_position:{packId:pack.id,position}},update:{rarityWeights:weights},create:{packId:pack.id,position,rarityWeights:weights}})}
const now=new Date(),seasonEnd=new Date(now.getTime()+90*864e5);await db.rankedSeason.upsert({where:{code:'S1_RIFTFALL'},update:{active:true},create:{code:'S1_RIFTFALL',name:'Riftfall Season',startsAt:new Date(now.getTime()-864e5),endsAt:seasonEnd,active:true}});const event=await db.gameEvent.upsert({where:{code:'ECLIPSE_NIGHT'},update:{startsAt:new Date(now.getTime()-864e5),endsAt:new Date(now.getTime()+21*864e5)},create:{code:'ECLIPSE_NIGHT',name:'Đêm Nhật Thực',description:'12 khe nứt mở dưới ánh trăng đen.',startsAt:new Date(now.getTime()-864e5),endsAt:new Date(now.getTime()+21*864e5),currencyCode:'ECLIPSE_TOKEN',stages:Array.from({length:12},(_,i)=>({number:i+1,boss:i===11}))}});if(await db.eventShopItem.count({where:{eventId:event.id}})===0)await db.eventShopItem.createMany({data:[{eventId:event.id,name:'Eclipse Card Back',cost:300,cosmetic:true},{eventId:event.id,name:'Limited Legendary Frame',cost:600,cosmetic:true,metadata:{variant:true,powerBonus:0}},{eventId:event.id,name:'Rift Dust Bundle',cost:150,cosmetic:false}]});await db.$disconnect();
