import { useEffect, useState } from 'react';
import { api } from './api';
import { cardArt } from './card-art';

const tutorialSteps = [
  ['1. Mục tiêu trận đấu','Hai thủ lĩnh bắt đầu với 100 Máu. Bạn thắng khi đưa Máu thủ lĩnh đối phương về 0.\n\nNếu bộ bài hết và chưa ai bị hạ, trận kết thúc ngay: người còn nhiều Máu thủ lĩnh hơn thắng; bằng Máu thì hòa.'],
  ['2. Chuẩn bị bộ bài','Một bộ bài hợp lệ có đúng 30 lá. Chọn một phe chính: IRONVALE hoặc ARCANUM. Bạn chỉ được dùng thẻ cùng phe và thẻ TRUNG LẬP.\n\nNên dùng ít nhất 16 đơn vị, 10–14 lá giá 0–3 và chỉ một số ít lá giá 8–10 để tránh kẹt tay đầu trận. Thẻ Huyền thoại, Thần thoại và Limited tối đa 1 bản; đa số thẻ khác tối đa 2 bản.'],
  ['3. Bài khởi đầu và tráo bài','Đầu trận, bộ bài được tráo ngẫu nhiên và mỗi người rút 5 lá. Ở bước đổi bài, bạn có thể đổi tối đa 2 lá không phù hợp; các lá đó được trả vào bộ rồi tráo lại.\n\nƯu tiên giữ đơn vị 1–3 năng lượng, một lá phòng thủ và một lá tạo lợi thế tài nguyên.'],
  ['4. Năng lượng và lượt','Mỗi lượt, giới hạn năng lượng cơ bản tăng dần đến 10. Năng lượng chưa dùng được cộng dồn sang lượt sau, tổng dự trữ tối đa 20.\n\nTrình tự nên dùng: kiểm tra hiệu ứng đầu lượt → dùng phép/tài nguyên → triệu hồi → tấn công → kiểm tra bàn → KẾT THÚC LƯỢT.'],
  ['5. Ba hàng trên bàn','Mỗi bên có Hàng trước, Hàng giữa và Hàng sau; mỗi hàng chứa tối đa 3 đơn vị. Chọn hàng trước khi triệu hồi.\n\nHàng không tự tăng/giảm sát thương, nhưng một số kỹ năng tác động đồng minh cùng hàng. Hãy tách các đơn vị quan trọng để tránh hiệu ứng diện rộng.'],
  ['6. Triệu hồi và tấn công','Đơn vị vừa triệu hồi thường chưa thể tấn công trong lượt đó. Đơn vị có XUNG KÍCH được tấn công ngay.\n\nĐể đánh: chọn đơn vị của bạn rồi chọn quân địch. Hai đơn vị gây sát thương cho nhau đồng thời, vì vậy chúng có thể cùng chết. Chỉ được đánh thủ lĩnh khi sân đối phương không còn đơn vị.'],
  ['7. Phép và chọn mục tiêu','Nhấn một lá Phép/Bẫy/Địa hình/Trang bị. Nếu kỹ năng ghi “mục tiêu” hoặc “một đơn vị”, bàn địch sẽ sáng để bạn chọn mục tiêu hợp lệ.\n\nHộ vệ không thể bị phép chọn mục tiêu. “Bỏ qua Khiên chắn” gây sát thương trực tiếp. Vết Nứt Nuốt Chửng chỉ tiêu diệt đơn vị có chi phí từ 3 trở xuống.'],
  ['8. Từ khóa phòng thủ','KHIÊU KHÍCH: phải tấn công đơn vị này trước các mục tiêu khác.\nKHIÊN CHẮN: chặn hoàn toàn nguồn sát thương đầu tiên rồi biến mất.\nHỘ VỆ: không thể bị chọn bởi phép đối phương; vẫn có thể bị tấn công hoặc chịu hiệu ứng diện rộng.\nCÂM LẶNG: vô hiệu từ khóa và Khiên hiện có của đơn vị.'],
  ['9. Từ khóa chiến thuật','XUNG KÍCH: được tấn công ngay trong lượt triệu hồi.\nTIÊN KIẾN: xem lá trên cùng; chọn giữ trên đầu hoặc đưa xuống cuối bộ bài.\nCỘNG HƯỞNG: nhận hiệu ứng bổ sung nếu bạn đã dùng phép trong lượt.\n\nKhi Tiên kiến đang chờ, phải giải quyết lựa chọn trước mọi hành động khác.'],
  ['10. Hiệu ứng theo thời điểm','“Triệu hồi” kích hoạt khi đơn vị vào bàn. “Hạ gục” chỉ kích hoạt nếu chính đơn vị đó kết liễu mục tiêu và còn sống. “Đầu lượt/Cuối lượt” tự kích hoạt đúng thời điểm.\n\nNhật ký bên phải ghi người dùng thẻ, sát thương, rút bài, năng lượng và chuyển lượt; dùng nó để kiểm tra chuỗi kỹ năng.'],
  ['11. Limited và seri máy chủ','Limited chỉ xuất hiện trong gói Ấn Phong Khe Nứt với tỷ lệ 0,5% cho từng lá mở. Mỗi bản thật có seri duy nhất và làm giảm kho toàn server.\n\nKhi đạt giới hạn 3, 10, 25 hoặc 50 bản tùy thẻ, lá đó vĩnh viễn rời khỏi gói. Tài khoản test không chiếm seri và không làm thay đổi kho thật. Limited không thể chế tạo hoặc phân rã.'],
  ['12. Mở gói và Bụi','Vàng/Bụi dùng để mua gói theo giá hiển thị. Mỗi gói có bảng tỷ lệ riêng; mở 10 gói tương đương 50 lần quay độc lập.\n\nThẻ thường bị trùng quá giới hạn sở hữu tự đổi thành Bụi. Trong Bộ thẻ, dùng Bụi để chế tạo thẻ còn thiếu hoặc phân rã thẻ không cần dùng.'],
  ['13. Các chế độ chơi','LUYỆN TẬP: học luật và thử bộ bài với AI.\nCHIẾN DỊCH: vượt bản đồ, luật màn và boss; boss dùng thẻ thật, không được cộng chỉ số ẩn.\nĐẤU THƯỜNG: tạo/phòng hoặc ghép trận không ảnh hưởng ELO.\nĐẤU XẾP HẠNG: ghép đối thủ thật, thắng/thua thay đổi ELO.\nSỰ KIỆN: hoàn thành màn giới hạn để nhận Xu và đổi vật phẩm.'],
  ['14. Mẹo và xử lý lỗi','Nếu nút bị khóa: kiểm tra đúng lượt, đủ năng lượng, hàng còn chỗ và đã giải quyết Tiên kiến chưa.\nNếu thấy “Access token expired/Failed to fetch”: tải lại trang, đăng nhập lại và kiểm tra API.\nNếu hiệu ứng cũ còn hiển thị: nhấn Ctrl+F5.\n\nMẹo chiến thuật: đừng dùng hết năng lượng chỉ vì có thể; dự trữ giúp tạo lượt bùng nổ, nhưng cần giữ đủ quân để bảo vệ thủ lĩnh.'],
];

export function Onboarding({ force=false, onClose }:{ force?:boolean;onClose:()=>void }) {
  const [step,setStep]=useState(0);
  const close=()=>{localStorage.setItem('chronicle-tutorial-complete','1');onClose()};
  return <div className="onboarding"><section className="onboarding-card guide-book"><header><div><small>CẨM NANG CHRONICLE RIFT</small><b>{step+1}/{tutorialSteps.length}</b></div><progress value={step+1} max={tutorialSteps.length}/></header><nav>{tutorialSteps.map((item,index)=><button className={index===step?'active':''} aria-label={item[0]} onClick={()=>setStep(index)} key={item[0]}>{index+1}</button>)}</nav><article><h2>{tutorialSteps[step]![0]}</h2><p>{tutorialSteps[step]![1]}</p></article><footer><button disabled={step===0} onClick={()=>setStep(value=>value-1)}>← Phần trước</button><button className="guide-close" onClick={close}>Đóng cẩm nang</button>{step<tutorialSteps.length-1?<button onClick={()=>setStep(value=>value+1)}>Phần tiếp →</button>:<button onClick={close}>Bắt đầu chơi</button>}</footer>{force&&<button className="link" onClick={close}>Đóng hướng dẫn</button>}</section></div>;
}

export function AdminPanel(){
 const[data,setData]=useState<any>(),[cards,setCards]=useState<any[]>([]);const[message,setMessage]=useState(''),[identity,setIdentity]=useState(''),[amount,setAmount]=useState(1_000_000),[granting,setGranting]=useState(false),[cardSearch,setCardSearch]=useState(''),[cardFaction,setCardFaction]=useState(''),[cardRarity,setCardRarity]=useState('');
 const load=()=>Promise.all([api('/admin/overview'),api<any[]>('/admin/cards')]).then(([overview,catalog])=>{setData(overview);setCards(catalog)}).catch(error=>setMessage((error as Error).message));useEffect(()=>{load()},[]);
 const update=async(id:string,input:any)=>{await api(`/admin/packs/${id}`,{method:'PATCH',body:JSON.stringify(input)});setMessage('Đã cập nhật cấu hình gói');load()};
 const grantGold=async(event:React.FormEvent)=>{event.preventDefault();try{setGranting(true);const result=await api<any>('/admin/users/gold',{method:'POST',body:JSON.stringify({identity,amount})});setMessage(`Đã cộng ${result.added.toLocaleString('vi-VN')} Vàng cho ${result.user.displayName}. Số dư mới: ${result.balance.toLocaleString('vi-VN')}`);setIdentity('')}catch(error){setMessage((error as Error).message)}finally{setGranting(false)}};
 if(!data)return <p>{message||'Đang tải quản trị…'}</p>;
 const visibleCards=cards.filter(card=>(!cardFaction||card.faction===cardFaction)&&(!cardRarity||card.rarity===cardRarity)&&(!cardSearch||`${card.code} ${card.name} ${card.description}`.toLocaleLowerCase('vi').includes(cardSearch.toLocaleLowerCase('vi'))));
 return <section className="admin-panel"><div className="admin-stats"><b>{data.users} tài khoản</b><b>{data.cards} thẻ</b><b>{data.openings} lượt mở gói</b></div><form className="admin-gold" onSubmit={grantGold}><div><small>CÔNG CỤ QUẢN TRỊ KINH TẾ</small><h2>Cộng Vàng cho nhân vật</h2><p>Nhập chính xác tên nhân vật hoặc email. Nếu có người trùng tên, hệ thống sẽ yêu cầu email.</p></div><label>Nhân vật hoặc email<input value={identity} onChange={event=>setIdentity(event.target.value)} placeholder="Ví dụ: nguyekie" required minLength={2}/></label><label>Số Vàng<input type="number" min="1" max="100000000" value={amount} onChange={event=>setAmount(Number(event.target.value))} required/></label><button disabled={granting}>{granting?'ĐANG CỘNG…':'CỘNG VÀNG'}</button></form><h2 className="admin-section-title">Cấu hình gói thẻ</h2>{data.packs.map((pack:any)=><article className="admin-pack" key={pack.id}><div><b>{pack.name}</b><small>{pack.code}</small></div><input type="number" defaultValue={pack.priceGold} onBlur={event=>update(pack.id,{priceGold:Number(event.target.value)})}/><button onClick={()=>update(pack.id,{enabled:!pack.enabled})}>{pack.enabled?'Đang bán':'Đã ẩn'}</button></article>)}<section className="admin-catalog"><header><div><small>THƯ VIỆN NỘI BỘ</small><h2>Toàn bộ thẻ trong game</h2><p>Hiển thị cả thẻ chưa sở hữu, thẻ đã ẩn và ấn bản Limited.</p></div><strong>{visibleCards.length}/{cards.length} THẺ</strong></header><div className="admin-card-filters"><input value={cardSearch} onChange={event=>setCardSearch(event.target.value)} placeholder="Tìm mã, tên hoặc kỹ năng…"/><select value={cardFaction} onChange={event=>setCardFaction(event.target.value)}><option value="">Tất cả phe</option><option>IRONVALE</option><option>ARCANUM</option><option>NEUTRAL</option></select><select value={cardRarity} onChange={event=>setCardRarity(event.target.value)}><option value="">Tất cả độ hiếm</option>{['COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ANCIENT','MYTHIC','CELESTIAL','LIMITED'].map(rarity=><option key={rarity}>{rarity}</option>)}</select></div><div className="admin-card-grid">{visibleCards.map(card=>{const art=cardArt(card.name,card.code);return <article key={card.id} className={`admin-card admin-card-${card.rarity.toLowerCase()}`}><div className={`admin-card-art ${art.className}`} style={art.style}/><div><small>{card.code} · {card.faction}</small><h3>{card.name}</h3><b>{card.type} · {card.rarity}</b><p>{card.description}</p><footer><span>✦ {card.cost}</span>{card.attack!==null&&<><span>⚔ {card.attack}</span><span>♥ {card.health}</span></>}<em>{card._count.owners} chủ sở hữu</em>{card.printLimit&&<strong>SERI {card.mintedCount}/{card.printLimit}</strong>}</footer></div></article>})}</div></section>{message&&<p className="admin-message">{message}</p>}</section>;
}
