import {useEffect,useRef,useState} from 'react';
import type {Socket} from 'socket.io-client';
import {cardArt} from './card-art';
import {resolveViewerId} from './pvp-state';
import './online-battle-campaign.css';

const rows=['FRONT','MIDDLE','BACK'] as const;
const rowName:Record<string,string>={FRONT:'Hàng trước',MIDDLE:'Hàng giữa',BACK:'Hàng sau'};
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
const limitedByName:Record<string,{slug:string;label:string}>={
 'thanh kiem valen':{slug:'valen-blade',label:'THÁNH KIẾM PHÁ TRẬN'},'hao luy cuoi cung':{slug:'last-bastion',label:'HÀO LŨY BẤT DIỆT'},'ky si nhat thuc':{slug:'eclipse-rider',label:'KỴ SĨ NHẬT THỰC'},
 'vuong mien hu khong':{slug:'void-crown',label:'VƯƠNG MIỆN HƯ KHÔNG'},'mua sao bang':{slug:'starfall',label:'MƯA SAO BĂNG'},'elira vuot thoi gian':{slug:'time-break',label:'ELIRA BẺ GÃY THỜI GIAN'},
 'nguoi giu can bang':{slug:'balance',label:'CÂN BẰNG TUYỆT ĐỐI'},'manh vo khoi nguyen':{slug:'origin-shard',label:'MẢNH VỠ KHỞI NGUYÊN'},'riftborn dau tien':{slug:'first-riftborn',label:'RIFTBORN THỨC TỈNH'},
};
const eventText=(text:string)=>text.replace('summoned','đã được triệu hồi').replace('damage','sát thương').replace('Unit died','Đơn vị đã bị tiêu diệt').replace('Shield absorbed damage','Khiên đã chặn sát thương').replace('Turn','Lượt');

function PvpCard({card,selected,onClick,onInspect,disabled=false}:{card:any;selected?:boolean;onClick?:()=>void;onInspect?:(card:any|null)=>void;disabled?:boolean}){const picture=cardArt(card.name,card.id??''),skills=(card.keywords??[]).join(' · ')||'Không có từ khóa';return <button title={`${card.name}\n${skills}\n${card.description??''}`} className={`battle-card ${selected?'selected':''} ${card.type.toLowerCase()}`} disabled={disabled} onMouseEnter={()=>onInspect?.(card)} onMouseLeave={()=>onInspect?.(null)} onFocus={()=>onInspect?.(card)} onBlur={()=>onInspect?.(null)} onClick={onClick}><span className="mana">{card.cost}</span><div className={`card-portrait ${picture.className}`} style={picture.style}><i>{card.type==='SPELL'?'✦':card.keywords?.includes('Taunt')?'♜':card.keywords?.includes('Rush')?'➶':'♞'}</i></div><strong>{card.name}</strong><small className="skill-text">{skills}</small>{card.type==='UNIT'&&<b className="stats battle-stats"><span className="attack-stat"><i>⚔</i>{card.currentAttack}</span><span className="health-stat"><i>♥</i>{card.currentHealth}</span></b>}</button>}

export function OnlineCampaignBattle({payload,matchId,mode,socket,status}:{payload:any;matchId:string;mode:string;socket:Socket|null;status:string}){
 const state=payload.state,viewerId=resolveViewerId(state),me=state.players.find((player:any)=>player.id===viewerId)??state.players[0],foe=state.players.find((player:any)=>player.id!==viewerId)??state.players[1],myTurn=state.activePlayerId===viewerId;
 const[row,setRow]=useState<'FRONT'|'MIDDLE'|'BACK'>('FRONT'),[attacker,setAttacker]=useState(''),[pendingSpell,setPendingSpell]=useState<any>(),[inspected,setInspected]=useState<any>(),[reveal,setReveal]=useState<any>(),[limited,setLimited]=useState<any>();
 const seenVersion=useRef(payload.version);
 const send=(action:any)=>socket?.emit('match:action',{matchId,actionId:crypto.randomUUID(),action});
 const allCards=(player:any)=>[...player.hand,...player.graveyard,...rows.flatMap(name=>player.board[name])];
 const announce=(card:any,owner:'keeper'|'ai')=>{const picture=cardArt(card.name,card.id??''),special=limitedByName[normalize(card.name)];if(special){setReveal(null);setLimited({key:Date.now(),...special,owner,picture});window.setTimeout(()=>setLimited(null),3200)}else{setReveal({key:Date.now(),owner,name:card.name,description:card.description??'',kind:card.type==='UNIT'?'TRIỆU HỒI':'MA PHÁP',picture});window.setTimeout(()=>setReveal(null),card.type==='UNIT'?1450:2200)}};
 useEffect(()=>{if(payload.version===seenVersion.current)return;seenVersion.current=payload.version;const event=[...state.events].reverse().find((item:any)=>item.playerId===foe.id&&item.sourceId&&['UNIT_SUMMONED','SPELL_CAST'].includes(item.type));if(event){const card=allCards(foe).find((item:any)=>item.instanceId===event.sourceId);if(card)announce(card,'ai')}},[payload.version]);
 const play=(card:any)=>{if(!myTurn||card.cost>me.energy)return;if(card.type==='UNIT'){announce(card,'keeper');send({type:'PLAY_CARD',cardInstanceId:card.instanceId,row});return}const targeted=normalize(card.description??'').includes('len muc tieu')||normalize(card.description??'').includes('mot don vi');if(targeted){setPendingSpell(card);setAttacker('')}else{announce(card,'keeper');send({type:'PLAY_CARD',cardInstanceId:card.instanceId})}};
 const target=(id:string)=>{if(pendingSpell){announce(pendingSpell,'keeper');send({type:'PLAY_CARD',cardInstanceId:pendingSpell.instanceId,targetId:id});setPendingSpell(undefined)}else if(attacker){send({type:'ATTACK',attackerId:attacker,targetId:id});setAttacker('')}};
 const foreseen=state.pendingForesee?.playerId===viewerId?me.deck[0]:undefined;
 return <div className={`battle online-campaign-battle ${myTurn?'':'ai-turn'}`}>
  {inspected&&(()=>{const picture=cardArt(inspected.name,inspected.id??''),skills=(inspected.keywords??[]).join(' · ')||'Không có từ khóa';return <aside className="card-inspector"><span className={`inspector-art ${picture.className}`} style={picture.style}/><span className="inspector-copy"><small>{inspected.type==='UNIT'?'ĐƠN VỊ':'MA PHÁP'} · {skills}</small><b>{inspected.name}</b><em>{inspected.description||'Không có mô tả kỹ năng.'}</em><span><i>✦ {inspected.cost}</i>{inspected.type==='UNIT'&&<><i>⚔ {inspected.currentAttack}</i><i>♥ {inspected.currentHealth}</i></>}</span></span></aside>})()}
  <div className="battle-ambience" aria-hidden="true"><i/><i/><i/></div>
  {reveal&&<div key={reveal.key} className={`spell-reveal ${reveal.owner}`}><div className={`spell-reveal-art ${reveal.picture.className}`} style={reveal.picture.style}/><section><small>{reveal.owner==='keeper'?'BẠN VỪA DÙNG':'ĐỐI THỦ VỪA DÙNG'} · {reveal.kind}</small><h2>{reveal.name}</h2><p>{reveal.description}</p></section></div>}
  {limited&&<div key={limited.key} className={`limited-cinematic limited-${limited.slug} owner-${limited.owner}`}><i/><i/><i/><span className={`limited-card-sigil ${limited.picture.className}`} style={limited.picture.style}/><span className="limited-particles">{Array.from({length:18},(_,index)=><i key={index}/>)}</span><div><small>ẤN BẢN GIỚI HẠN ĐƯỢC KÍCH HOẠT</small><b>{limited.label}</b></div></div>}
  {foreseen&&<div className="foresee-choice"><section><small>TIÊN KIẾN · LÁ TRÊN CÙNG</small><div className={`foresee-art ${cardArt(foreseen.name,foreseen.id??'').className}`} style={cardArt(foreseen.name,foreseen.id??'').style}/><h2>{foreseen.name}</h2><p>{foreseen.description}</p><footer><button onClick={()=>send({type:'RESOLVE_FORESEE',choice:'KEEP'})}>GIỮ TRÊN ĐẦU</button><button onClick={()=>send({type:'RESOLVE_FORESEE',choice:'BOTTOM'})}>ĐƯA XUỐNG CUỐI</button></footer></section></div>}
  <div className="tutorial"><b>{mode==='RANKED'?'ĐẤU XẾP HẠNG':'ĐẤU THƯỜNG'}</b><span>{pendingSpell?`Đã chọn ${pendingSpell.name} · chọn mục tiêu đối phương`:attacker?'Chọn đơn vị đối phương để tấn công':status}</span></div>
  <div className="battle-top"><button className="leader enemy" onClick={()=>target(foe.id)}><span>ĐỐI THỦ TRỰC TUYẾN</span><b>♥ {foe.leaderHealth}</b><small>{foe.hand.length} lá trên tay · {foe.deck.length} lá trong bộ</small></button><div className="turn-orb"><b>Lượt {state.turn}</b><span>{myTurn?'LƯỢT CỦA BẠN':'LƯỢT ĐỐI THỦ'}</span></div></div>
  {([...rows].reverse()).map(name=><div className={`battle-row enemy-row ${pendingSpell?'targeting':''}`} key={`enemy-${name}`}><label>{rowName[name]}</label>{foe.board[name].map((card:any)=><PvpCard key={card.instanceId} card={card} onInspect={setInspected} onClick={()=>target(card.instanceId)}/>)}</div>)}
  <div className="rift-line"><span>◆</span> KHE NỨT CHRONICLE <span>◆</span></div>
  {rows.map(name=><div className={`battle-row ${row===name?'chosen-row':''}`} key={name}><label onClick={()=>setRow(name)}>{rowName[name]}</label>{me.board[name].map((card:any)=><PvpCard key={card.instanceId} card={card} onInspect={setInspected} selected={attacker===card.instanceId} onClick={()=>{if(myTurn){setAttacker(card.instanceId);setPendingSpell(undefined)}}}/>)}</div>)}
  <div className="row-picker"><b>Triệu hồi vào:</b>{rows.map(name=><button className={row===name?'active':''} onClick={()=>setRow(name)} key={name}>{rowName[name]}</button>)}</div>
  <div className="hand"><div className="resource"><b>♥ {me.leaderHealth}</b><strong>✦ {me.energy} · +{me.maxEnergy}/lượt</strong><small>Dự trữ tối đa 20 · Bộ bài: {me.deck.length} · Nghĩa địa: {me.graveyard.length}</small></div><div className="hand-cards">{me.hand.map((card:any)=><PvpCard key={card.instanceId} card={card} selected={pendingSpell?.instanceId===card.instanceId} onInspect={setInspected} disabled={!myTurn||card.cost>me.energy} onClick={()=>play(card)}/>)}</div><div className="pvp-campaign-actions"><button className="end" disabled={!myTurn} onClick={()=>{setPendingSpell(undefined);setAttacker('');send({type:'END_TURN'})}}>KẾT THÚC LƯỢT</button><button onClick={()=>send({type:'CONCEDE'})}>ĐẦU HÀNG</button></div></div>
  <section className="action-history"><header><b>NHẬT KÝ THAO TÁC</b><small>{Math.min(16,state.events.length)} hành động gần nhất</small></header><div>{state.events.length===0?<p>Những lần dùng thẻ, tấn công và kết thúc lượt sẽ xuất hiện tại đây.</p>:state.events.slice(-16).reverse().map((event:any,index:number)=><article className={event.playerId===viewerId?'mine':'theirs'} key={`${payload.version}-${index}`}><i>L{state.turn}</i><span><b>{eventText(event.message)}</b></span></article>)}</div></section>
  <div className="combat-log"><b>Phiên PvP #{matchId.slice(-6)}:</b>{state.events.slice(-4).map((event:any,index:number)=><span key={index}>{eventText(event.message)}</span>)}</div>
 </div>;
}
