import{useEffect,useState}from'react';import{api}from'./api';import{cardArt}from'./card-art';
const rarity:Record<string,string>={COMMON:'Thường',UNCOMMON:'Ít gặp',RARE:'Hiếm',EPIC:'Sử thi',LEGENDARY:'Huyền thoại',ANCIENT:'Cổ Đại',MYTHIC:'Thần thoại',CELESTIAL:'Thiên Giới',LIMITED:'Giới hạn'};
export function PackShop(){
 const[data,setData]=useState<any>({packs:[],currency:[]}),[cards,setCards]=useState<any[]>([]),[busy,setBusy]=useState(false),[detail,setDetail]=useState<any>(),[visible,setVisible]=useState(0);
 const load=()=>api<any>('/packs').then(setData);useEffect(()=>{load()},[]);useEffect(()=>{if(cards.length&&visible<cards.length){const timer=window.setTimeout(()=>setVisible(v=>v+1),430);return()=>clearTimeout(timer)}},[cards,visible]);
 const open=async(id:string)=>{setBusy(true);setCards([]);setVisible(0);try{const r=await api<any>(`/packs/${id}/open`,{method:'POST',body:JSON.stringify({requestId:crypto.randomUUID()})});await new Promise(x=>setTimeout(x,700));setCards(r.opened??r.history.result);load()}finally{setBusy(false)}};
 const picture=(c:any)=>cardArt(c.name,c.code);
 return <><div className="wallet">{data.testMode&&<strong className="sandbox-badge"/>}{data.currency.map((x:any)=><b key={x.code}>{x.code}: {data.testMode?'∞':x.balance.toLocaleString('vi-VN')}</b>)}</div>
 <div className="packs pack-catalog">{data.packs.map((p:any)=><article key={p.id} className={p.code==='RIFT_SEAL'?'seal-pack':''}><div className={`pack-art art-${p.code.length%8}`}><span>✦</span><i>CHRONICLE</i></div><h2>{p.name}</h2><p>{p.code==='RIFT_SEAL'?'Gói duy nhất có thể xuất hiện thẻ đánh số giới hạn.':'5 thẻ · Không chứa thẻ đánh số giới hạn.'}</p><button className="pack-open-button" disabled={busy} onClick={()=>open(p.id)}>{busy?'ĐANG MỞ…':`MỞ GÓI · ${data.testMode?'∞':p.priceGold.toLocaleString('vi-VN')} VÀNG`}</button></article>)}</div>
 {busy&&<div className="opening-stage active"><div className="rift-pack">✦</div></div>}
 {cards.length>0&&<section className="loot-result"><header><div><small>KẾT QUẢ</small><h2>Đang lật thẻ · Nhấn vào thẻ để đọc chi tiết</h2></div><b>{visible}/{cards.length}</b></header><div className="loot-cards">{cards.map((c,i)=>{const pic=picture(c);return <article key={i} style={pic.style} onClick={()=>i<visible&&setDetail(c)} className={`loot-card ${i<visible?'shown':''} ${c.rarity.toLowerCase()}`}><div className="card-back">✦</div><div className={`loot-art ${pic.className}`}/><small>{rarity[c.rarity]??c.rarity}</small><h3>{c.name}</h3><div className="loot-stats"><b>✦ {c.cost}</b>{c.attack!==null&&<><b>⚔ {c.attack}</b><b>♥ {c.health}</b></>}</div><p>{c.description}</p></article>})}</div><button className="open-again" onClick={()=>{setCards([]);setVisible(0)}}>ĐÓNG</button></section>}
 {detail&&(()=>{const pic=picture(detail);return <div className="card-detail-overlay" onClick={()=>setDetail(null)}><article onClick={e=>e.stopPropagation()} className="card-detail"><button onClick={()=>setDetail(null)}>×</button><div style={pic.style} className={`loot-art ${pic.className}`}/><small>{rarity[detail.rarity]}</small><h2>{detail.name}</h2><div className="detail-stats"><b>Năng lượng {detail.cost}</b>{detail.attack!==null&&<><b>Công {detail.attack}</b><b>Máu {detail.health}</b></>}</div><div className="detail-keywords">{(detail.keywords??[]).map((k:string)=><span key={k}>{k}</span>)}</div><p>{detail.description}</p>{detail.serial&&<strong>SERI {detail.serial}/{detail.printLimit}</strong>}</article></div>})()}</>}
