import {Router} from 'express'; import argon2 from 'argon2'; import jwt from 'jsonwebtoken'; import crypto from 'node:crypto'; import {z} from 'zod'; import {db} from './db.js'; import {config} from './config.js'; import {HttpError,requireAuth} from './http.js'; import {starterCodes} from '@chronicle/card-data';
const router=Router(); const credentials=z.object({email:z.string().email().transform(v=>v.toLowerCase()),password:z.string().min(8).max(128)}); const register=credentials.extend({displayName:z.string().trim().min(2).max(30)}); const hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');
const issue=async(user:{id:string;role:'USER'|'ADMIN'})=>{const accessToken=jwt.sign({role:user.role},config.JWT_ACCESS_SECRET,{subject:user.id,expiresIn:'15m'});const raw=jwt.sign({kind:'refresh'},config.JWT_REFRESH_SECRET,{subject:user.id,expiresIn:'7d',jwtid:crypto.randomUUID()});await db.refreshToken.create({data:{userId:user.id,tokenHash:hash(raw),expiresAt:new Date(Date.now()+7*864e5)}});return {accessToken,refreshToken:raw};};
const publicUser=(u:any)=>({id:u.id,email:u.email,role:u.role,profile:u.profile});
router.post('/register',async(req,res)=>{const input=register.parse(req.body);if(await db.user.findUnique({where:{email:input.email}}))throw new HttpError(409,'EMAIL_TAKEN','Email đã được đăng ký');const passwordHash=await argon2.hash(input.password);const user=await db.$transaction(async tx=>{const u=await tx.user.create({data:{email:input.email,passwordHash,profile:{create:{displayName:input.displayName}}},include:{profile:true}});await tx.userCurrency.createMany({data:[{userId:u.id,code:'GOLD',balance:250000},{userId:u.id,code:'DUST',balance:500},{userId:u.id,code:'GEM',balance:0}]});const available=await tx.card.findMany({where:{code:{in:[...starterCodes.IRONVALE,...starterCodes.ARCANUM]}}});await tx.userCard.createMany({data:available.map(c=>({userId:u.id,cardId:c.id,quantity:2}))});for(const faction of ['IRONVALE','ARCANUM'] as const){const wanted=starterCodes[faction],selected=available.filter(c=>wanted.includes(c.code)).slice(0,15);await tx.deck.create({data:{userId:u.id,name:`Bộ khởi đầu ${faction==='IRONVALE'?'Ironvale':'Arcanum'}`,faction,isDefault:faction==='IRONVALE',cards:{create:selected.map((c,i)=>({cardId:c.id,quantity:2,position:i}))}}});}return u;});const tokens=await issue(user as any);res.status(201).json({user:publicUser(user),...tokens});});
router.post('/login',async(req,res)=>{const input=credentials.parse(req.body);const user=await db.user.findUnique({where:{email:input.email},include:{profile:true}});if(!user||!await argon2.verify(user.passwordHash,input.password))throw new HttpError(401,'INVALID_CREDENTIALS','Email or password is incorrect');res.json({user:publicUser(user),...await issue(user as any)});});
router.post('/refresh',async(req,res)=>{const token=z.object({refreshToken:z.string()}).parse(req.body).refreshToken;let claims:any;try{claims=jwt.verify(token,config.JWT_REFRESH_SECRET);}catch{throw new HttpError(401,'INVALID_REFRESH_TOKEN','Refresh token is invalid or expired')}const stored=await db.refreshToken.findUnique({where:{tokenHash:hash(token)},include:{user:true}});if(!stored||stored.revokedAt||stored.expiresAt<new Date()||stored.userId!==claims.sub)throw new HttpError(401,'INVALID_REFRESH_TOKEN','Refresh token is invalid or expired');await db.refreshToken.update({where:{id:stored.id},data:{revokedAt:new Date()}});res.json(await issue(stored.user as any));});
router.post('/logout',async(req,res)=>{const token=z.object({refreshToken:z.string()}).parse(req.body).refreshToken;await db.refreshToken.updateMany({where:{tokenHash:hash(token),revokedAt:null},data:{revokedAt:new Date()}});res.status(204).end();});
router.get('/me',requireAuth,async(req,res)=>{const user=await db.user.findUniqueOrThrow({where:{id:req.auth!.sub},include:{profile:true}});res.json(publicUser(user));}); export default router;
