import { z } from 'zod';
export const cardSchema=z.object({code:z.string().regex(/^[A-Z]{2,3}-\d{3}$/),name:z.string().min(2),description:z.string().min(2),type:z.enum(['UNIT','SPELL','TRAP','TERRAIN','EQUIPMENT']),faction:z.enum(['IRONVALE','ARCANUM','NEUTRAL']),rarity:z.enum(['COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ANCIENT','MYTHIC','CELESTIAL','LIMITED']),cost:z.number().int().min(0).max(10),attack:z.number().int().nonnegative().nullable(),health:z.number().int().positive().nullable(),keywords:z.array(z.string()),collectible:z.boolean().default(true),printLimit:z.number().int().positive().optional()}).superRefine((c,ctx)=>{if(c.type==='UNIT'&&(c.attack===null||c.health===null))ctx.addIssue({code:'custom',message:'Unit requires attack and health'});if(c.rarity==='LIMITED'&&!c.printLimit)ctx.addIssue({code:'custom',message:'Limited card requires print limit'});});
export type CardSeed=z.infer<typeof cardSchema>;
const names={IRONVALE:['Tân Binh Khiên','Thợ Rèn Tiền Tuyến','Cung Thủ Thành Trì','Hiệp Sĩ Tro Tàn','Vệ Binh Cổng Bắc','Kỵ Sĩ Thép','Chỉ Huy Tiền Tuyến','Người Mang Khiên','Pháo Thủ Thành Đồng','Cận Vệ Valen','Mệnh Lệnh Phòng Thủ','Bức Tường Sắt','Rèn Khiên Khẩn Cấp','Đội Hình Chữ V','Tiếng Kèn Xung Trận','Giáp Phản Quang','Nỏ Thành Pháo','Lời Thề Ironvale','Đại Tướng Valen','Pháo Đài Di Động'],ARCANUM:['Học Viên Tia Chớp','Thủ Thư Bí Thuật','Pháp Sư Tập Sự','Người Giữ Tinh Tú','Kẻ Dệt Ảo Ảnh','Học Giả Hư Không','Thuật Sĩ Hồ Quang','Người Đọc Vận Mệnh','Kỵ Sĩ Ma Pháp','Giám Hộ Thư Viện','Ảo Ảnh Sao Chép','Khóa Ma Lực','Bão Hồ Quang','Tia Chớp Phân Nhánh','Dòng Chảy Mana','Gương Bí Thuật','Dịch Chuyển','Nhà Tiên Tri Elira','Vòng Lặp Arcane','Đại Pháp Sư Orin'],NEUTRAL:['Lính Đánh Thuê','Thương Nhân Lang Thang','Chó Săn Khe Nứt','Người Chữa Thương','Bản Đồ Cổ','Bình Năng Lượng','Cú Đánh Chính Xác','Cổng Dịch Chuyển']};
const keywordsByFaction={IRONVALE:['Taunt','Shield'],ARCANUM:['Foresee','Resonance'],NEUTRAL:[]} as const;
const coreCards:CardSeed[]=Object.entries(names).flatMap(([faction,list])=>list.map((name,i)=>{const spell=i>=10||faction==='NEUTRAL'&&i>=4; const legendary=i===18||i===19; return cardSchema.parse({code:`${faction==='IRONVALE'?'IV':faction==='ARCANUM'?'AR':'NE'}-${String(i+1).padStart(3,'0')}`,name,description:spell?`Hiệu ứng chiến thuật ${name.toLowerCase()}.`:`Đơn vị ${faction.toLowerCase()} đáng tin cậy.`,type:spell?(i%5===3?'TRAP':i%7===0?'EQUIPMENT':'SPELL'):'UNIT',faction,rarity:legendary?'LEGENDARY':i%7===5?'EPIC':i%5===4?'RARE':i%3===2?'UNCOMMON':'COMMON',cost:Math.min(8,1+(i%8)),attack:spell?null:1+(i%6),health:spell?null:2+(i%7),keywords:spell?[]:[...(keywordsByFaction[faction as keyof typeof keywordsByFaction]??[])].slice(0,i%3),collectible:true});}));
const expansionNames={IRONVALE:['Ngự Lâm Quân Hoàng Kim','Rồng Máy Thành Đồng','Nữ Vương Khiên Thép','Chiến Xa Bình Minh','Thợ Rèn Huyền Tích','Cờ Lệnh Bất Khuất','Pháo Hoa Thành Trì','Thánh Kiếm Valen','Hào Lũy Cuối Cùng','Kỵ Sĩ Nhật Thực'],ARCANUM:['Rồng Tinh Vân','Phù Thủy Nguyệt Thực','Người Dệt Thời Gian','Thư Viện Sống','Mắt Bão Vĩnh Hằng','Tinh Cầu Tiên Tri','Cổng Sao Gãy','Vương Miện Hư Không','Mưa Sao Băng','Elira Vượt Thời Gian'],NEUTRAL:['Phượng Hoàng Khe Nứt','Kẻ Du Hành Vô Danh','Đồng Hồ Tận Thế','Vương Miện Chronicle','La Bàn Định Mệnh','Linh Thú Sao Rơi','Chìa Khóa Cổ Giới','Người Giữ Cân Bằng','Mảnh Vỡ Khởi Nguyên','Riftborn Đầu Tiên']} as const;
type LimitedProfile=Pick<CardSeed,'description'|'type'|'cost'|'attack'|'health'|'keywords'|'printLimit'>;
const limitedProfiles:Record<string,LimitedProfile>={
 'IV-028':{description:'Khiêu khích · Khiên chắn · Xung kích. Triệu hồi: toàn bộ đồng minh nhận +3 Công/+5 Máu và Khiên chắn; thủ lĩnh hồi 5 Máu. Nếu sống sót giao tranh, nhận +2 Công. Chỉ có 50 bản.',type:'UNIT',cost:7,attack:14,health:20,keywords:['Taunt','Shield','Rush'],printLimit:50},
 'IV-029':{description:'Thi triển: toàn bộ đồng minh nhận Khiên chắn, +4 Công và +12 Máu; thủ lĩnh hồi 15 Máu. Chỉ có 25 bản.',type:'SPELL',cost:7,attack:null,health:null,keywords:[],printLimit:25},
 'IV-030':{description:'Khiên chắn · Xung kích · Hộ vệ. Hạ gục: nhận vĩnh viễn +6 Công/+4 Máu, hoàn 3 Năng lượng và hồi 3 Máu cho thủ lĩnh. Chỉ có 10 bản.',type:'UNIT',cost:9,attack:24,health:28,keywords:['Shield','Rush','Ward'],printLimit:10},
 'AR-028':{description:'Hộ vệ · Tiên kiến · Cộng hưởng. Triệu hồi: đánh cắp 4 Công từ đơn vị địch mạnh nhất; nếu không có địch, rút 2 lá. Chỉ có 50 bản.',type:'UNIT',cost:7,attack:12,health:18,keywords:['Ward','Foresee','Resonance'],printLimit:50},
 'AR-029':{description:'Đại phép: gây 28 sát thương chia đều cho mọi kẻ địch và 10 sát thương lên thủ lĩnh, sau đó rút 2 lá và nhận 3 Năng lượng. Chỉ có 25 bản.',type:'SPELL',cost:8,attack:null,health:null,keywords:[],printLimit:25},
 'AR-030':{description:'Hộ vệ · Tiên kiến · Cộng hưởng. Triệu hồi: rút 2 lá và nhận 4 Năng lượng. Cuối lượt: nếu đã dùng phép, nhận +3 Công/+3 Máu. Chỉ có 10 bản.',type:'UNIT',cost:10,attack:18,health:25,keywords:['Ward','Foresee','Resonance'],printLimit:10},
 'NE-028':{description:'Khiêu khích · Khiên chắn · Hộ vệ. Triệu hồi: đặt Máu hai thủ lĩnh bằng trung bình hiện tại. Chỉ có 50 bản.',type:'UNIT',cost:7,attack:16,health:26,keywords:['Taunt','Shield','Ward'],printLimit:50},
 'NE-029':{description:'Thi triển: gây 22 sát thương lên mục tiêu; nếu hạ gục, rút 3 lá, nhận 2 Năng lượng và hồi 15 Máu cho thủ lĩnh. Chỉ có 25 bản.',type:'SPELL',cost:6,attack:null,health:null,keywords:[],printLimit:25},
 'NE-030':{description:'Khiên chắn · Xung kích · Hộ vệ. Triệu hồi: gây 7 sát thương lên đơn vị địch yếu nhất và triệu hồi lại đồng minh mạnh nhất từ nghĩa địa với 1 Máu. Chỉ có 10 bản.',type:'UNIT',cost:10,attack:26,health:30,keywords:['Shield','Rush','Ward'],printLimit:10},
};
const expansionCards:CardSeed[]=Object.entries(expansionNames).flatMap(([faction,list])=>list.map((name,i)=>{const code=`${faction==='IRONVALE'?'IV':faction==='ARCANUM'?'AR':'NE'}-${String(i+21).padStart(3,'0')}`;const profile=limitedProfiles[code];const type=profile?.type??(i===5?'TERRAIN':i===6?'EQUIPMENT':i===8?'SPELL':'UNIT');return cardSchema.parse({code,name,description:profile?.description??'Thẻ Biên Niên Sử mở rộng với hiệu ứng chiến thuật độc đáo.',type,faction,rarity:profile?'LIMITED':i===6?'MYTHIC':i===5?'LEGENDARY':i%2?'EPIC':'RARE',cost:profile?.cost??Math.min(10,3+i),attack:profile?.attack??(type==='UNIT'?3+i:null),health:profile?.health??(type==='UNIT'?5+i:null),keywords:profile?.keywords??(type==='UNIT'?(faction==='IRONVALE'?['Taunt','Shield']:faction==='ARCANUM'?['Foresee','Resonance']:['Rush']):[]),collectible:true,...(profile?{printLimit:profile.printLimit}:{})});}));
const frontierNames={IRONVALE:['Hộ Vệ Cầu Đá','Đội Trưởng Bình Minh','Pháo Thủ Bão Sắt','Kỵ Binh Sư Tử','Thợ Máy Hoàng Gia','Giáp Binh Núi Đen','Người Giữ Quân Kỳ','Thành Lũy Biết Đi','Mũi Giáo Phán Quyết','Đại Bàng Chiến Trận'],ARCANUM:['Học Giả Sao Chổi','Pháp Sư Thủy Tinh','Người Gọi Thiên Lôi','Kẻ Bẻ Cong Không Gian','Giám Hộ Mộng Giới','Nhà Luyện Kim Ánh Trăng','Thợ Săn Linh Hồn','Hải Đăng Tinh Tú','Sứ Giả Ngân Hà','Rồng Con Hư Không'],NEUTRAL:['Cá Voi Trên Mây','Người Canh Cổng Cổ','Thợ Săn Di Vật','Cây Cổ Thụ Biết Đi','Kỵ Sĩ Mặt Nạ','Sói Tinh Thạch','Cỗ Máy Tiên Tri','Chim Ưng Tuyết','Hòn Đảo Trôi Dạt','Bóng Ma Sa Mạc']} as const;
const effects=['Triệu hồi: nhận +1 Công trong lượt này.','Khiên chắn: chặn hoàn toàn nguồn sát thương đầu tiên.','Khiêu khích: đối thủ phải tấn công đơn vị này trước.','Xung kích: có thể tấn công ngay trong lượt được triệu hồi.','Hạ gục: hồi 2 Máu cho thủ lĩnh.','Đầu lượt: nhận +1 Máu tối đa.','Khi bị đánh: gây lại 1 sát thương cho kẻ tấn công.','Đồng minh cùng hàng nhận +1 Công.','Cuối lượt: rút 1 lá nếu còn ít hơn 3 lá trên tay.','Triệu hồi: gây 2 sát thương lên đơn vị yếu nhất của địch.'];
const frontierCards:CardSeed[]=Object.entries(frontierNames).flatMap(([faction,list])=>list.map((name,i)=>cardSchema.parse({code:`${faction==='IRONVALE'?'IV':faction==='ARCANUM'?'AR':'NE'}-${String(i+31).padStart(3,'0')}`,name,description:effects[i]!,type:'UNIT',faction,rarity:i===9?'MYTHIC':i>=7?'LEGENDARY':i>=4?'EPIC':i>=2?'RARE':'UNCOMMON',cost:1+i%8,attack:2+i%6,health:3+(i*2)%7,keywords:i%3===0?['Rush']:i%3===1?(faction==='IRONVALE'?['Taunt','Shield']:['Foresee','Resonance']):['Ward'],collectible:true})));
const ascendantNames={IRONVALE:['Vua Thành Trì Aurel','Thiên Sứ Chiến Tranh','Cự Thần Thép Đỏ','Thánh Đường Bất Diệt','Kiếm Vương Bình Minh','Sư Tử Hoàng Kim','Pháo Đài Trên Mây','Kỵ Sĩ Cổ Đại','Ngai Vàng Sấm Sét','Đại Đế Ironvale'],ARCANUM:['Nữ Thần Tinh Tú','Rồng Thiên Hà','Thư Viện Vô Tận','Người Viết Lại Thời Gian','Mặt Trời Lam','Oracle Thiên Giới','Vương Miện Ngân Hà','Pháp Sư Cổ Đại','Trái Tim Vũ Trụ','Đấng Sáng Tạo Orin'],NEUTRAL:['Thần Thú Khởi Nguyên','Phượng Hoàng Thiên Giới','Người Đưa Tin Vĩnh Cửu','Cánh Cổng Sáng Thế','Leviathan Khe Nứt','Cây Thế Giới','Mặt Nạ Cổ Thần','Đồng Hồ Vĩnh Hằng','Tinh Linh Đầu Tiên','Kẻ Đi Qua Muôn Cõi']}as const;
const ascendantCards:CardSeed[]=Object.entries(ascendantNames).flatMap(([faction,list])=>list.map((name,i)=>{const rarity=i>=8?'CELESTIAL':i>=5?'MYTHIC':i>=2?'ANCIENT':'LEGENDARY';return cardSchema.parse({code:`${faction==='IRONVALE'?'IV':faction==='ARCANUM'?'AR':'NE'}-${String(i+41).padStart(3,'0')}`,name,description:i>=8?'Thiên giới: miễn nhiễm phép trong lượt triệu hồi; toàn bộ đồng minh nhận +3 Công/+3 Máu.':'Cổ lực: khi triệu hồi, gây 4 sát thương và rút 1 lá.',type:'UNIT',faction,rarity,cost:7+i%4,attack:8+i,health:10+i,keywords:i>=8?['Shield','Rush','Ward']:i>=5?['Shield','Rush']:['Taunt','Shield'],collectible:true})}));
const reservoirCards:CardSeed[]=[
 {code:'IV-051',name:'Kỹ Sư Tích Năng',description:'Triệu hồi: tiêu tối đa 2 Năng lượng còn lại; nhận +1 Công/+1 Máu cho mỗi điểm.',type:'UNIT',faction:'IRONVALE',rarity:'EPIC',cost:3,attack:3,health:4,keywords:['Shield'],collectible:true},
 {code:'IV-052',name:'Thành Lũy Dự Trữ',description:'Cuối lượt: nếu còn ít nhất 3 Năng lượng, nhận Khiên chắn.',type:'UNIT',faction:'IRONVALE',rarity:'LEGENDARY',cost:5,attack:4,health:8,keywords:['Taunt'],collectible:true},
 {code:'IV-053',name:'Đao Phủ Lò Rèn',description:'Hạ gục: hoàn lại 2 Năng lượng.',type:'UNIT',faction:'IRONVALE',rarity:'MYTHIC',cost:6,attack:7,health:5,keywords:['Rush'],collectible:true},
 {code:'AR-051',name:'Dòng Chảy Nghịch',description:'Thi triển: hồi 8 Máu cho thủ lĩnh.',type:'SPELL',faction:'ARCANUM',rarity:'EPIC',cost:4,attack:null,health:null,keywords:[],collectible:true},
 {code:'AR-052',name:'Khoảnh Khắc Vô Tận',description:'Thi triển: rút 3 lá.',type:'SPELL',faction:'ARCANUM',rarity:'LEGENDARY',cost:5,attack:null,health:null,keywords:[],collectible:true},
 {code:'AR-053',name:'Pháp Sư Dẫn Mana',description:'Triệu hồi: nhận 2 Năng lượng.',type:'UNIT',faction:'ARCANUM',rarity:'MYTHIC',cost:4,attack:3,health:5,keywords:['Foresee','Resonance'],collectible:true},
 {code:'NE-051',name:'Kẻ Thu Gom Tàn Dư',description:'Cuối lượt: nếu còn ít nhất 5 Năng lượng, nhận +2 Công/+2 Máu.',type:'UNIT',faction:'NEUTRAL',rarity:'EPIC',cost:4,attack:4,health:5,keywords:[],collectible:true},
 {code:'NE-052',name:'Bình Mana Nứt Vỡ',description:'Thi triển: nhận 3 Năng lượng.',type:'SPELL',faction:'NEUTRAL',rarity:'RARE',cost:2,attack:null,health:null,keywords:[],collectible:true},
 {code:'NE-053',name:'Vết Nứt Nuốt Chửng',description:'Thi triển: tiêu diệt một đơn vị có chi phí từ 3 trở xuống.',type:'SPELL',faction:'NEUTRAL',rarity:'MYTHIC',cost:4,attack:null,health:null,keywords:[],collectible:true},
].map(card=>cardSchema.parse(card));
const dawnCards:CardSeed[]=[
 {code:'IV-054',name:'Trinh Sát Cầm Đuốc',description:'Xung kích: có thể tấn công ngay trong lượt được triệu hồi.',type:'UNIT',faction:'IRONVALE',rarity:'COMMON',cost:1,attack:1,health:2,keywords:['Rush'],collectible:true},
 {code:'IV-055',name:'Sứ Giả Khiên Nhẹ',description:'Khiên chắn: chặn hoàn toàn nguồn sát thương đầu tiên.',type:'UNIT',faction:'IRONVALE',rarity:'UNCOMMON',cost:2,attack:2,health:2,keywords:['Shield'],collectible:true},
 {code:'IV-056',name:'Cận Vệ Đồng Hồ',description:'Khiêu khích · Khiên chắn. Một phòng tuyến nhỏ nhưng bền bỉ.',type:'UNIT',faction:'IRONVALE',rarity:'RARE',cost:1,attack:1,health:3,keywords:['Taunt','Shield'],collectible:true},
 {code:'IV-057',name:'Trống Lệnh Tiền Quân',description:'Xung kích: mở nhịp tấn công sớm cho đội hình Ironvale.',type:'UNIT',faction:'IRONVALE',rarity:'EPIC',cost:3,attack:3,health:4,keywords:['Rush'],collectible:true},
 {code:'AR-054',name:'Tập Sự Tia Lam',description:'Tiên kiến: xem trước lá trên cùng và có thể đưa xuống cuối bộ bài.',type:'UNIT',faction:'ARCANUM',rarity:'COMMON',cost:1,attack:1,health:1,keywords:['Foresee'],collectible:true},
 {code:'AR-055',name:'Bướm Phù Văn',description:'Cộng hưởng: nhận thêm hiệu ứng sau khi bạn đã dùng phép trong lượt.',type:'UNIT',faction:'ARCANUM',rarity:'UNCOMMON',cost:0,attack:0,health:1,keywords:['Resonance'],collectible:true},
 {code:'AR-056',name:'Nét Chữ Khai Mở',description:'Thi triển: gây 1 sát thương lên mục tiêu. Nếu mục tiêu bị hạ, rút 1 lá.',type:'SPELL',faction:'ARCANUM',rarity:'RARE',cost:0,attack:null,health:null,keywords:[],collectible:true},
 {code:'AR-057',name:'Cáo Pha Lê',description:'Xung kích · Hộ vệ. Linh thú nhỏ lách qua phép của đối thủ.',type:'UNIT',faction:'ARCANUM',rarity:'EPIC',cost:2,attack:2,health:2,keywords:['Rush','Ward'],collectible:true},
 {code:'NE-054',name:'Người Dẫn Đường Đèn Cũ',description:'Triệu hồi: nhận +1 Công trong lượt này. Nếu sống sót, nhận +1 Máu.',type:'UNIT',faction:'NEUTRAL',rarity:'COMMON',cost:1,attack:1,health:2,keywords:[],collectible:true},
 {code:'NE-055',name:'Bọ Khe Nứt',description:'Khiên chắn: lớp tinh thể chặn nguồn sát thương đầu tiên.',type:'UNIT',faction:'NEUTRAL',rarity:'UNCOMMON',cost:0,attack:0,health:2,keywords:['Shield'],collectible:true},
 {code:'NE-056',name:'Dược Sư Lữ Hành',description:'Hộ vệ: không thể bị chọn bởi phép của đối thủ.',type:'UNIT',faction:'NEUTRAL',rarity:'RARE',cost:2,attack:1,health:3,keywords:['Ward'],collectible:true},
 {code:'NE-057',name:'Đồng Xu May Mắn',description:'Thi triển: gây 1 sát thương lên mục tiêu. Đồng minh yếu nhất nhận +1 Máu.',type:'SPELL',faction:'NEUTRAL',rarity:'LEGENDARY',cost:1,attack:null,health:null,keywords:[],collectible:true},
].map(card=>cardSchema.parse(card));
const rawCards:CardSeed[]=[...coreCards,...expansionCards,...frontierCards,...ascendantCards,...reservoirCards,...dawnCards];
const cardCorrections:Record<string,Partial<CardSeed>>={
 'IV-011':{type:'SPELL',description:'Thi triển: toàn bộ đồng minh nhận +2 Công trong lượt này.'},
 'IV-012':{type:'TERRAIN',description:'Địa hình: toàn bộ đồng minh nhận +4 Máu và Khiên chắn.'},
 'IV-013':{type:'EQUIPMENT',description:'Trang bị: đồng minh yếu nhất nhận +1 Công/+4 Máu và Khiên chắn.'},
 'IV-014':{type:'TERRAIN',description:'Địa hình: toàn bộ đồng minh nhận +2 Công/+2 Máu.'},
 'IV-015':{type:'SPELL',description:'Thi triển: toàn bộ đồng minh nhận +3 Công trong lượt này.'},
 'IV-016':{type:'EQUIPMENT',description:'Trang bị: đồng minh yếu nhất nhận Khiên chắn; khi bị đánh, gây lại 2 sát thương.'},
 'IV-017':{type:'EQUIPMENT',description:'Trang bị: đồng minh yếu nhất nhận +5 Công.'},
 'IV-018':{type:'SPELL',description:'Thi triển: thủ lĩnh hồi 7 Máu; toàn bộ đồng minh nhận +1 Công/+1 Máu.'},
 'IV-019':{type:'UNIT',attack:8,health:10,keywords:['Taunt','Shield'],description:'Triệu hồi: toàn bộ đồng minh nhận +2 Công. Hạ gục: hồi 2 Máu cho thủ lĩnh.'},
 'IV-020':{type:'TERRAIN',description:'Địa hình: toàn bộ đồng minh nhận +6 Máu.'},
 'AR-011':{type:'SPELL',description:'Thi triển: đồng minh mạnh nhất nhận +3 Công/+3 Máu.'},
 'AR-012':{type:'TRAP',description:'Bẫy: gây 5 sát thương lên đơn vị địch vừa được triệu hồi.'},
 'AR-013':{type:'SPELL',description:'Thi triển: gây 7 sát thương lên mục tiêu.'},
 'AR-014':{type:'SPELL',description:'Thi triển: gây 4 sát thương lên tối đa hai đơn vị địch.'},
 'AR-015':{type:'TERRAIN',description:'Địa hình: nhận 3 Năng lượng và rút 1 lá.'},
 'AR-016':{type:'TRAP',description:'Bẫy: chặn phép tiếp theo của đối thủ và rút 1 lá.'},
 'AR-017':{type:'SPELL',description:'Thi triển: đưa một đơn vị địch về tay chủ sở hữu.'},
 'AR-018':{type:'UNIT',attack:5,health:9,keywords:['Foresee','Resonance'],description:'Tiên kiến · Cộng hưởng. Cuối lượt: nếu đã dùng phép, rút 1 lá.'},
 'AR-019':{type:'TRAP',description:'Bẫy: phép tiếp theo bạn dùng được phát lại với một nửa sát thương.'},
 'AR-020':{type:'UNIT',attack:9,health:8,keywords:['Ward','Foresee'],description:'Triệu hồi: rút 2 lá. Mỗi khi dùng phép, nhận +1 Công/+1 Máu.'},
 'NE-005':{type:'EQUIPMENT',description:'Trang bị: rút 2 lá rồi đưa 1 lá trên tay xuống cuối bộ bài.'},
 'NE-006':{type:'EQUIPMENT',description:'Trang bị: nhận 3 Năng lượng.'},
 'NE-007':{type:'SPELL',description:'Thi triển: gây 6 sát thương lên mục tiêu; bỏ qua Khiên chắn.'},
 'NE-008':{type:'TERRAIN',description:'Địa hình: rút 1 lá và nhận 2 Năng lượng.'},
 'IV-026':{type:'TERRAIN',description:'Địa hình: toàn bộ đồng minh nhận +2 Công và Khiên chắn.'},
 'IV-027':{type:'EQUIPMENT',description:'Trang bị: đồng minh yếu nhất nhận +4 Công/+4 Máu.'},
 'AR-026':{type:'TERRAIN',description:'Địa hình: rút 2 lá và nhận 2 Năng lượng.'},
 'AR-027':{type:'EQUIPMENT',description:'Trang bị: đồng minh mạnh nhất nhận Hộ vệ và +3 Công/+3 Máu.'},
 'NE-026':{type:'TERRAIN',description:'Địa hình: toàn bộ đồng minh nhận +3 Máu; rút 1 lá.'},
 'NE-027':{type:'EQUIPMENT',description:'Trang bị: đồng minh yếu nhất nhận +2 Công/+5 Máu và Xung kích.'},
};
const keywordRules:Record<string,string>={Taunt:'Khiêu khích: đối thủ phải tấn công đơn vị này trước.',Shield:'Khiên chắn: chặn hoàn toàn nguồn sát thương đầu tiên.',Rush:'Xung kích: có thể tấn công ngay trong lượt được triệu hồi.',Foresee:'Tiên kiến: xem trước lá trên cùng và có thể đưa xuống cuối bộ bài.',Resonance:'Cộng hưởng: nhận thêm hiệu ứng khi bạn đã dùng phép trong lượt.',Ward:'Hộ vệ: không thể bị chọn bởi phép của đối thủ.'};
export const cards:CardSeed[]=rawCards.map((original,i)=>{const card=cardSchema.parse({...original,...cardCorrections[original.code]});if(card.rarity==='LIMITED'||card.description.includes(':'))return card;const rules=card.keywords.map(k=>keywordRules[k]).filter(Boolean).join(' ');const description=card.type==='UNIT'?`${rules||'Triệu hồi: nhận +1 Công trong lượt này.'} ${i%2?'Khi hạ gục mục tiêu, hồi 1 Máu cho thủ lĩnh.':'Nếu sống sót giao tranh, nhận +1 Máu.'}`:`Thi triển: gây ${2+i%4} sát thương lên mục tiêu. ${i%2?'Nếu mục tiêu bị hạ, rút 1 lá.':'Đồng minh yếu nhất nhận +1 Máu.'}`;return cardSchema.parse({...card,description})});
export const starterCodes={IRONVALE:cards.filter(c=>c.faction==='IRONVALE').slice(0,15).flatMap(c=>[c.code,c.code]),ARCANUM:cards.filter(c=>c.faction==='ARCANUM').slice(0,15).flatMap(c=>[c.code,c.code])};
